/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.apis

import com.openai.infrastructure.ApiClient
import com.openai.infrastructure.ApiResponse
import com.openai.infrastructure.ClientError
import com.openai.infrastructure.ClientException
import com.openai.infrastructure.MultiValueMap
import com.openai.infrastructure.RequestConfig
import com.openai.infrastructure.RequestMethod
import com.openai.infrastructure.ResponseType
import com.openai.infrastructure.ServerError
import com.openai.infrastructure.ServerException
import com.openai.infrastructure.Success
import com.openai.infrastructure.toMultiValue
import com.openai.models.CreateResponse
import com.openai.models.Includable
import com.openai.models.Response
import com.openai.models.ResponseItemList
import com.squareup.moshi.Json
import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

class ResponsesApi(
    basePath: kotlin.String = defaultBasePath,
    client: Call.Factory = ApiClient.defaultClient,
) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties()
                .getProperty(ApiClient.baseUrlKey, "https://api.openai.com/v1")
        }
    }

    /**
     * POST /responses Creates a model response. Provide
     * [text](/docs/guides/text) or [image](/docs/guides/images) inputs to
     * generate [text](/docs/guides/text) or
     * [JSON](/docs/guides/structured-outputs) outputs. Have the model call your
     * own [custom code](/docs/guides/function-calling) or use built-in
     * [tools](/docs/guides/tools) like
     * [web search](/docs/guides/tools-web-search) or
     * [file search](/docs/guides/tools-file-search) to use your own data as
     * input for the model&#39;s response.
     *
     * @param createResponse
     * @return Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational
     *   or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun createResponse(createResponse: CreateResponse): Response {
        val localVarResponse =
            createResponseWithHttpInfo(createResponse = createResponse)

        return when (localVarResponse.responseType) {
            ResponseType.Success ->
                (localVarResponse as Success<*>).data as Response
            ResponseType.Informational ->
                throw UnsupportedOperationException(
                    "Client does not support Informational responses."
                )
            ResponseType.Redirection ->
                throw UnsupportedOperationException(
                    "Client does not support Redirection responses."
                )
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * POST /responses Creates a model response. Provide
     * [text](/docs/guides/text) or [image](/docs/guides/images) inputs to
     * generate [text](/docs/guides/text) or
     * [JSON](/docs/guides/structured-outputs) outputs. Have the model call your
     * own [custom code](/docs/guides/function-calling) or use built-in
     * [tools](/docs/guides/tools) like
     * [web search](/docs/guides/tools-web-search) or
     * [file search](/docs/guides/tools-file-search) to use your own data as
     * input for the model&#39;s response.
     *
     * @param createResponse
     * @return ApiResponse<Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createResponseWithHttpInfo(
        createResponse: CreateResponse
    ): ApiResponse<Response?> {
        val localVariableConfig =
            createResponseRequestConfig(createResponse = createResponse)

        return request<CreateResponse, Response>(localVariableConfig)
    }

    /**
     * To obtain the request config of the operation createResponse
     *
     * @param createResponse
     * @return RequestConfig
     */
    fun createResponseRequestConfig(
        createResponse: CreateResponse
    ): RequestConfig<CreateResponse> {
        val localVariableBody = createResponse
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/responses",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody,
        )
    }

    /**
     * DELETE /responses/{response_id} Deletes a model response with the given
     * ID.
     *
     * @param responseId The ID of the response to delete.
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational
     *   or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun deleteResponse(responseId: kotlin.String): Unit {
        val localVarResponse =
            deleteResponseWithHttpInfo(responseId = responseId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational ->
                throw UnsupportedOperationException(
                    "Client does not support Informational responses."
                )
            ResponseType.Redirection ->
                throw UnsupportedOperationException(
                    "Client does not support Redirection responses."
                )
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * DELETE /responses/{response_id} Deletes a model response with the given
     * ID.
     *
     * @param responseId The ID of the response to delete.
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteResponseWithHttpInfo(
        responseId: kotlin.String
    ): ApiResponse<Unit?> {
        val localVariableConfig =
            deleteResponseRequestConfig(responseId = responseId)

        return request<Unit, Unit>(localVariableConfig)
    }

    /**
     * To obtain the request config of the operation deleteResponse
     *
     * @param responseId The ID of the response to delete.
     * @return RequestConfig
     */
    fun deleteResponseRequestConfig(
        responseId: kotlin.String
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path =
                "/responses/{response_id}"
                    .replace(
                        "{" + "response_id" + "}",
                        encodeURIComponent(responseId.toString()),
                    ),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody,
        )
    }

    /**
     * GET /responses/{response_id} Retrieves a model response with the given
     * ID.
     *
     * @param responseId The ID of the response to retrieve.
     * @param include Specify additional output data to include in the response.
     *   Currently supported values are: - &#x60;file_search_call.results&#x60;:
     *   Include the search results of the file search tool call. -
     *   &#x60;message.input_image.image_url&#x60;: Include image urls from the
     *   input message. - &#x60;computer_call_output.output.image_url&#x60;:
     *   Include image urls from the computer call output. (optional)
     * @return Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational
     *   or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun getResponse(
        responseId: kotlin.String,
        include: kotlin.collections.List<Includable>? = null,
    ): Response {
        val localVarResponse =
            getResponseWithHttpInfo(responseId = responseId, include = include)

        return when (localVarResponse.responseType) {
            ResponseType.Success ->
                (localVarResponse as Success<*>).data as Response
            ResponseType.Informational ->
                throw UnsupportedOperationException(
                    "Client does not support Informational responses."
                )
            ResponseType.Redirection ->
                throw UnsupportedOperationException(
                    "Client does not support Redirection responses."
                )
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /responses/{response_id} Retrieves a model response with the given
     * ID.
     *
     * @param responseId The ID of the response to retrieve.
     * @param include Specify additional output data to include in the response.
     *   Currently supported values are: - &#x60;file_search_call.results&#x60;:
     *   Include the search results of the file search tool call. -
     *   &#x60;message.input_image.image_url&#x60;: Include image urls from the
     *   input message. - &#x60;computer_call_output.output.image_url&#x60;:
     *   Include image urls from the computer call output. (optional)
     * @return ApiResponse<Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getResponseWithHttpInfo(
        responseId: kotlin.String,
        include: kotlin.collections.List<Includable>?,
    ): ApiResponse<Response?> {
        val localVariableConfig =
            getResponseRequestConfig(responseId = responseId, include = include)

        return request<Unit, Response>(localVariableConfig)
    }

    /**
     * To obtain the request config of the operation getResponse
     *
     * @param responseId The ID of the response to retrieve.
     * @param include Specify additional output data to include in the response.
     *   Currently supported values are: - &#x60;file_search_call.results&#x60;:
     *   Include the search results of the file search tool call. -
     *   &#x60;message.input_image.image_url&#x60;: Include image urls from the
     *   input message. - &#x60;computer_call_output.output.image_url&#x60;:
     *   Include image urls from the computer call output. (optional)
     * @return RequestConfig
     */
    fun getResponseRequestConfig(
        responseId: kotlin.String,
        include: kotlin.collections.List<Includable>?,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap =
            mutableMapOf<
                    kotlin.String,
                    kotlin.collections.List<kotlin.String>,
                >()
                .apply {
                    if (include != null) {
                        put("include", toMultiValue(include.toList(), "multi"))
                    }
                }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path =
                "/responses/{response_id}"
                    .replace(
                        "{" + "response_id" + "}",
                        encodeURIComponent(responseId.toString()),
                    ),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody,
        )
    }

    /** enum for parameter order */
    enum class OrderListInputItems(val value: kotlin.String) {
        @Json(name = "asc") asc("asc"),
        @Json(name = "desc") desc("desc");

        /**
         * Override [toString()] to avoid using the enum variable name as the
         * value, and instead use the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are
         * different, and ensures that the client sends the correct enum values
         * to the server always.
         */
        override fun toString(): kotlin.String = "$value"
    }

    /**
     * GET /responses/{response_id}/input_items Returns a list of input items
     * for a given response.
     *
     * @param responseId The ID of the response to retrieve input items for.
     * @param limit A limit on the number of objects to be returned. Limit can
     *   range between 1 and 100, and the default is 20. (optional, default
     *   to 20)
     * @param order The order to return the input items in. Default is
     *   &#x60;asc&#x60;. - &#x60;asc&#x60;: Return the input items in ascending
     *   order. - &#x60;desc&#x60;: Return the input items in descending order.
     *   (optional)
     * @param after An item ID to list items after, used in pagination.
     *   (optional)
     * @param before An item ID to list items before, used in pagination.
     *   (optional)
     * @return ResponseItemList
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational
     *   or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun listInputItems(
        responseId: kotlin.String,
        limit: kotlin.Int? = 20,
        order: OrderListInputItems? = null,
        after: kotlin.String? = null,
        before: kotlin.String? = null,
    ): ResponseItemList {
        val localVarResponse =
            listInputItemsWithHttpInfo(
                responseId = responseId,
                limit = limit,
                order = order,
                after = after,
                before = before,
            )

        return when (localVarResponse.responseType) {
            ResponseType.Success ->
                (localVarResponse as Success<*>).data as ResponseItemList
            ResponseType.Informational ->
                throw UnsupportedOperationException(
                    "Client does not support Informational responses."
                )
            ResponseType.Redirection ->
                throw UnsupportedOperationException(
                    "Client does not support Redirection responses."
                )
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /responses/{response_id}/input_items Returns a list of input items
     * for a given response.
     *
     * @param responseId The ID of the response to retrieve input items for.
     * @param limit A limit on the number of objects to be returned. Limit can
     *   range between 1 and 100, and the default is 20. (optional, default
     *   to 20)
     * @param order The order to return the input items in. Default is
     *   &#x60;asc&#x60;. - &#x60;asc&#x60;: Return the input items in ascending
     *   order. - &#x60;desc&#x60;: Return the input items in descending order.
     *   (optional)
     * @param after An item ID to list items after, used in pagination.
     *   (optional)
     * @param before An item ID to list items before, used in pagination.
     *   (optional)
     * @return ApiResponse<ResponseItemList?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listInputItemsWithHttpInfo(
        responseId: kotlin.String,
        limit: kotlin.Int?,
        order: OrderListInputItems?,
        after: kotlin.String?,
        before: kotlin.String?,
    ): ApiResponse<ResponseItemList?> {
        val localVariableConfig =
            listInputItemsRequestConfig(
                responseId = responseId,
                limit = limit,
                order = order,
                after = after,
                before = before,
            )

        return request<Unit, ResponseItemList>(localVariableConfig)
    }

    /**
     * To obtain the request config of the operation listInputItems
     *
     * @param responseId The ID of the response to retrieve input items for.
     * @param limit A limit on the number of objects to be returned. Limit can
     *   range between 1 and 100, and the default is 20. (optional, default
     *   to 20)
     * @param order The order to return the input items in. Default is
     *   &#x60;asc&#x60;. - &#x60;asc&#x60;: Return the input items in ascending
     *   order. - &#x60;desc&#x60;: Return the input items in descending order.
     *   (optional)
     * @param after An item ID to list items after, used in pagination.
     *   (optional)
     * @param before An item ID to list items before, used in pagination.
     *   (optional)
     * @return RequestConfig
     */
    fun listInputItemsRequestConfig(
        responseId: kotlin.String,
        limit: kotlin.Int?,
        order: OrderListInputItems?,
        after: kotlin.String?,
        before: kotlin.String?,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap =
            mutableMapOf<
                    kotlin.String,
                    kotlin.collections.List<kotlin.String>,
                >()
                .apply {
                    if (limit != null) {
                        put("limit", listOf(limit.toString()))
                    }
                    if (order != null) {
                        put("order", listOf(order.value))
                    }
                    if (after != null) {
                        put("after", listOf(after.toString()))
                    }
                    if (before != null) {
                        put("before", listOf(before.toString()))
                    }
                }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path =
                "/responses/{response_id}/input_items"
                    .replace(
                        "{" + "response_id" + "}",
                        encodeURIComponent(responseId.toString()),
                    ),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody,
        )
    }

    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder()
            .scheme("http")
            .host("localhost")
            .addPathSegment(uriComponent)
            .build()
            .encodedPathSegments[0]
}
