/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openai.apis.EmbeddingsApi
import com.openai.models.CreateEmbeddingRequest
import com.openai.models.CreateEmbeddingResponse

class EmbeddingsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EmbeddingsApi
        //val apiInstance = EmbeddingsApi()

        // to test createEmbedding
        should("test createEmbedding") {
            // uncomment below to test createEmbedding
            //val createEmbeddingRequest : CreateEmbeddingRequest =  // CreateEmbeddingRequest | 
            //val result : CreateEmbeddingResponse = apiInstance.createEmbedding(createEmbeddingRequest)
            //result shouldBe ("TODO")
        }

    }
}
