/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.apis

import io.kotlintest.specs.ShouldSpec

class RealtimeApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RealtimeApi
        // val apiInstance = RealtimeApi()

        // to test createRealtimeSession
        should("test createRealtimeSession") {
            // uncomment below to test createRealtimeSession
            // val realtimeSessionCreateRequest : RealtimeSessionCreateRequest =
            //  // RealtimeSessionCreateRequest | Create an ephemeral API key
            // with the given session configuration.
            // val result : RealtimeSessionCreateResponse =
            // apiInstance.createRealtimeSession(realtimeSessionCreateRequest)
            // result shouldBe ("TODO")
        }

        // to test createRealtimeTranscriptionSession
        should("test createRealtimeTranscriptionSession") {
            // uncomment below to test createRealtimeTranscriptionSession
            // val realtimeTranscriptionSessionCreateRequest :
            // RealtimeTranscriptionSessionCreateRequest =  //
            // RealtimeTranscriptionSessionCreateRequest | Create an ephemeral
            // API key with the given session configuration.
            // val result : RealtimeTranscriptionSessionCreateResponse =
            // apiInstance.createRealtimeTranscriptionSession(realtimeTranscriptionSessionCreateRequest)
            // result shouldBe ("TODO")
        }
    }
}
