/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @param type The type of the file citation. Always `file_citation`.
 * @param index The index of the file in the list of files.
 * @param fileId The ID of the file.
 * @param url The URL of the web resource.
 * @param title The title of the web resource.
 * @param startIndex The index of the first character of the URL citation in the
 *   message.
 * @param endIndex The index of the last character of the URL citation in the
 *   message.
 */
data class Annotation(

    /* The type of the file citation. Always `file_citation`.  */
    @Json(name = "type") val type: Annotation.Type,

    /* The index of the file in the list of files.  */
    @Json(name = "index") val index: kotlin.Int,

    /* The ID of the file.  */
    @Json(name = "file_id") val fileId: kotlin.String,

    /* The URL of the web resource.  */
    @Json(name = "url") val url: kotlin.String,

    /* The title of the web resource.  */
    @Json(name = "title") val title: kotlin.String,

    /* The index of the first character of the URL citation in the message.  */
    @Json(name = "start_index") val startIndex: kotlin.Int,

    /* The index of the last character of the URL citation in the message.  */
    @Json(name = "end_index") val endIndex: kotlin.Int,
) {

    /**
     * The type of the file citation. Always `file_citation`.
     *
     * Values: file_citation,url_citation,file_path
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "file_citation") file_citation("file_citation"),
        @Json(name = "url_citation") url_citation("url_citation"),
        @Json(name = "file_path") file_path("file_path"),
    }
}
