/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models


import com.squareup.moshi.Json

/**
 * The service account that performed the audit logged action.
 *
 * @param id The service account id.
 */


data class AuditLogActorServiceAccount (

    /* The service account id. */
    @Json(name = "id")
    val id: kotlin.String? = null

) {


}

