/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @param `object` The type of object being deleted.
 * @param id The ID of the chat completion that was deleted.
 * @param deleted Whether the chat completion was deleted.
 */
data class ChatCompletionDeleted(

    /* The type of object being deleted. */
    @Json(name = "object") val `object`: ChatCompletionDeleted.`Object`,

    /* The ID of the chat completion that was deleted. */
    @Json(name = "id") val id: kotlin.String,

    /* Whether the chat completion was deleted. */
    @Json(name = "deleted") val deleted: kotlin.Boolean,
) {

    /**
     * The type of object being deleted.
     *
     * Values: chatPeriodCompletionPeriodDeleted
     */
    @JsonClass(generateAdapter = false)
    enum class `Object`(val value: kotlin.String) {
        @Json(name = "chat.completion.deleted")
        chatPeriodCompletionPeriodDeleted("chat.completion.deleted")
    }
}
