/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @param content The contents of the message.
 * @param refusal The refusal message generated by the model.
 * @param role The role of the author of this message.
 * @param id The identifier of the chat message.
 * @param toolCalls The tool calls generated by the model, such as function
 *   calls.
 * @param annotations Annotations for the message, when applicable, as when
 *   using the [web search tool](/docs/guides/tools-web-search?api-mode=chat).
 * @param functionCall
 * @param audio
 */
data class ChatCompletionMessageListDataInner(

    /* The contents of the message. */
    @Json(name = "content") val content: kotlin.String?,

    /* The refusal message generated by the model. */
    @Json(name = "refusal") val refusal: kotlin.String?,

    /* The role of the author of this message. */
    @Json(name = "role") val role: ChatCompletionMessageListDataInner.Role,

    /* The identifier of the chat message. */
    @Json(name = "id") val id: kotlin.String,

    /* The tool calls generated by the model, such as function calls. */
    @Json(name = "tool_calls")
    val toolCalls: kotlin.collections.List<ChatCompletionMessageToolCall>? =
        null,

    /* Annotations for the message, when applicable, as when using the [web search tool](/docs/guides/tools-web-search?api-mode=chat).  */
    @Json(name = "annotations")
    val annotations:
        kotlin.collections.List<
            ChatCompletionResponseMessageAnnotationsInner
        >? =
        null,
    @Json(name = "function_call")
    @Deprecated(message = "This property is deprecated.")
    val functionCall: ChatCompletionResponseMessageFunctionCall? = null,
    @Json(name = "audio") val audio: ChatCompletionResponseMessageAudio? = null,
) {

    /**
     * The role of the author of this message.
     *
     * Values: assistant
     */
    @JsonClass(generateAdapter = false)
    enum class Role(val value: kotlin.String) {
        @Json(name = "assistant") assistant("assistant")
    }
}
