/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models


import com.squareup.moshi.Json

/**
 * Data about a previous audio response from the model.  [Learn more](/docs/guides/audio). 
 *
 * @param id Unique identifier for a previous audio response from the model. 
 */


data class ChatCompletionRequestAssistantMessageAudio (

    /* Unique identifier for a previous audio response from the model.  */
    @Json(name = "id")
    val id: kotlin.String

) {


}

