/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * An object representing a list of chat completion messages.
 *
 * @param `object` The type of this object. It is always set to \"list\".
 * @param `data` An array of chat completion message objects.
 * @param firstId The identifier of the first chat message in the data array.
 * @param lastId The identifier of the last chat message in the data array.
 * @param hasMore Indicates whether there are more chat messages available.
 */
data class ChatCompletionMessageList(

    /* The type of this object. It is always set to \"list\".  */
    @Json(name = "object")
    val `object`: ChatCompletionMessageList.`Object` = `Object`.list,

    /* An array of chat completion message objects.  */
    @Json(name = "data")
    val `data`: kotlin.collections.List<ChatCompletionMessageListDataInner>,

    /* The identifier of the first chat message in the data array. */
    @Json(name = "first_id") val firstId: kotlin.String,

    /* The identifier of the last chat message in the data array. */
    @Json(name = "last_id") val lastId: kotlin.String,

    /* Indicates whether there are more chat messages available. */
    @Json(name = "has_more") val hasMore: kotlin.Boolean,
) {

    /**
     * The type of this object. It is always set to \"list\".
     *
     * Values: list
     */
    @JsonClass(generateAdapter = false)
    enum class `Object`(val value: kotlin.String) {
        @Json(name = "list") list("list")
    }
}
