/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @param type The type of the code interpreter text output. Always `logs`.
 * @param logs The logs of the code interpreter tool call.
 * @param files
 */
data class CodeInterpreterToolOutput(

    /* The type of the code interpreter text output. Always `logs`.  */
    @Json(name = "type") val type: CodeInterpreterToolOutput.Type,

    /* The logs of the code interpreter tool call.  */
    @Json(name = "logs") val logs: kotlin.String,
    @Json(name = "files")
    val files: kotlin.collections.List<CodeInterpreterFileOutputFilesInner>,
) {

    /**
     * The type of the code interpreter text output. Always `logs`.
     *
     * Values: logs,files
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "logs") logs("logs"),
        @Json(name = "files") files("files"),
    }
}
