/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A tool that runs code.
 *
 * @param type The type of the code interpreter tool. Always `code_interpreter`.
 * @param fileIds The IDs of the files to run the code on.
 */
data class CodeInterpreterTool(

    /* The type of the code interpreter tool. Always `code_interpreter`.  */
    @Json(name = "type") val type: CodeInterpreterTool.Type,

    /* The IDs of the files to run the code on.  */
    @Json(name = "file_ids") val fileIds: kotlin.collections.List<kotlin.String>,
) {

    /**
     * The type of the code interpreter tool. Always `code_interpreter`.
     *
     * Values: code_interpreter
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "code_interpreter") code_interpreter("code_interpreter")
    }
}
