/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A computer screenshot image used with the computer use tool.
 *
 * @param type Specifies the event type. For a computer screenshot, this
 *   property is always set to `computer_screenshot`.
 * @param imageUrl The URL of the screenshot image.
 * @param fileId The identifier of an uploaded file that contains the
 *   screenshot.
 */
data class ComputerScreenshotImage(

    /* Specifies the event type. For a computer screenshot, this property is  always set to `computer_screenshot`.  */
    @Json(name = "type")
    val type: ComputerScreenshotImage.Type = Type.computer_screenshot,

    /* The URL of the screenshot image. */
    @Json(name = "image_url") val imageUrl: kotlin.String? = null,

    /* The identifier of an uploaded file that contains the screenshot. */
    @Json(name = "file_id") val fileId: kotlin.String? = null,
) {

    /**
     * Specifies the event type. For a computer screenshot, this property is
     * always set to `computer_screenshot`.
     *
     * Values: computer_screenshot
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "computer_screenshot")
        computer_screenshot("computer_screenshot")
    }
}
