/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @param type Specifies the event type. For a click action, this property is
 *   always set to `click`.
 * @param button Indicates which mouse button was pressed during the click. One
 *   of `left`, `right`, `wheel`, `back`, or `forward`.
 * @param x The x-coordinate where the scroll occurred.
 * @param y The y-coordinate where the scroll occurred.
 * @param path An array of coordinates representing the path of the drag action.
 *   Coordinates will appear as an array of objects, eg ``` [ { x: 100, y: 200
 *   }, { x: 200, y: 300 } ] ```
 * @param propertyKeys The combination of keys the model is requesting to be
 *   pressed. This is an array of strings, each representing a key.
 * @param scrollX The horizontal scroll distance.
 * @param scrollY The vertical scroll distance.
 * @param text The text to type.
 */
data class ComputerAction(

    /* Specifies the event type. For a click action, this property is  always set to `click`.  */
    @Json(name = "type") val type: ComputerAction.Type = Type.click,

    /* Indicates which mouse button was pressed during the click. One of `left`, `right`, `wheel`, `back`, or `forward`.  */
    @Json(name = "button") val button: ComputerAction.Button,

    /* The x-coordinate where the scroll occurred.  */
    @Json(name = "x") val x: kotlin.Int,

    /* The y-coordinate where the scroll occurred.  */
    @Json(name = "y") val y: kotlin.Int,

    /* An array of coordinates representing the path of the drag action. Coordinates will appear as an array of objects, eg ``` [   { x: 100, y: 200 },   { x: 200, y: 300 } ] ```  */
    @Json(name = "path") val path: kotlin.collections.List<Coordinate>,

    /* The combination of keys the model is requesting to be pressed. This is an array of strings, each representing a key.  */
    @Json(name = "keys")
    val propertyKeys: kotlin.collections.List<kotlin.String>,

    /* The horizontal scroll distance.  */
    @Json(name = "scroll_x") val scrollX: kotlin.Int,

    /* The vertical scroll distance.  */
    @Json(name = "scroll_y") val scrollY: kotlin.Int,

    /* The text to type.  */
    @Json(name = "text") val text: kotlin.String,
) {

    /**
     * Specifies the event type. For a click action, this property is always set
     * to `click`.
     *
     * Values: click,double_click,drag,keypress,move,screenshot,scroll,type,wait
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "click") click("click"),
        @Json(name = "double_click") double_click("double_click"),
        @Json(name = "drag") drag("drag"),
        @Json(name = "keypress") keypress("keypress"),
        @Json(name = "move") move("move"),
        @Json(name = "screenshot") screenshot("screenshot"),
        @Json(name = "scroll") scroll("scroll"),
        @Json(name = "type") type("type"),
        @Json(name = "wait") wait("wait"),
    }

    /**
     * Indicates which mouse button was pressed during the click. One of `left`,
     * `right`, `wheel`, `back`, or `forward`.
     *
     * Values: left,right,wheel,back,forward
     */
    @JsonClass(generateAdapter = false)
    enum class Button(val value: kotlin.String) {
        @Json(name = "left") left("left"),
        @Json(name = "right") right("right"),
        @Json(name = "wheel") wheel("wheel"),
        @Json(name = "back") back("back"),
        @Json(name = "forward") forward("forward"),
    }
}
