/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A tool call to a computer use tool. See the
 * [computer use guide](/docs/guides/tools-computer-use) for more information.
 *
 * @param type The type of the computer call. Always `computer_call`.
 * @param id The unique ID of the computer call.
 * @param callId An identifier used when responding to the tool call with
 *   output.
 * @param action
 * @param pendingSafetyChecks The pending safety checks for the computer call.
 * @param status The status of the item. One of `in_progress`, `completed`, or
 *   `incomplete`. Populated when items are returned via API.
 */
data class ComputerToolCall(

    /* The type of the computer call. Always `computer_call`. */
    @Json(name = "type") val type: ComputerToolCall.Type = Type.computer_call,

    /* The unique ID of the computer call. */
    @Json(name = "id") val id: kotlin.String,

    /* An identifier used when responding to the tool call with output.  */
    @Json(name = "call_id") val callId: kotlin.String,
    @Json(name = "action") val action: ComputerAction,

    /* The pending safety checks for the computer call.  */
    @Json(name = "pending_safety_checks")
    val pendingSafetyChecks:
        kotlin.collections.List<ComputerToolCallSafetyCheck>,

    /* The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.  */
    @Json(name = "status") val status: ComputerToolCall.Status,
) {

    /**
     * The type of the computer call. Always `computer_call`.
     *
     * Values: computer_call
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "computer_call") computer_call("computer_call")
    }

    /**
     * The status of the item. One of `in_progress`, `completed`, or
     * `incomplete`. Populated when items are returned via API.
     *
     * Values: in_progress,completed,incomplete
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "in_progress") in_progress("in_progress"),
        @Json(name = "completed") completed("completed"),
        @Json(name = "incomplete") incomplete("incomplete"),
    }
}
