/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The output of a computer tool call.
 *
 * @param type The type of the computer tool call output. Always
 *   `computer_call_output`.
 * @param callId The ID of the computer tool call that produced the output.
 * @param output
 * @param id The ID of the computer tool call output.
 * @param acknowledgedSafetyChecks The safety checks reported by the API that
 *   have been acknowledged by the developer.
 * @param status The status of the message input. One of `in_progress`,
 *   `completed`, or `incomplete`. Populated when input items are returned via
 *   API.
 */
data class ComputerToolCallOutput(

    /* The type of the computer tool call output. Always `computer_call_output`.  */
    @Json(name = "type")
    val type: ComputerToolCallOutput.Type = Type.computer_call_output,

    /* The ID of the computer tool call that produced the output.  */
    @Json(name = "call_id") val callId: kotlin.String,
    @Json(name = "output") val output: ComputerScreenshotImage,

    /* The ID of the computer tool call output.  */
    @Json(name = "id") val id: kotlin.String? = null,

    /* The safety checks reported by the API that have been acknowledged by the  developer.  */
    @Json(name = "acknowledged_safety_checks")
    val acknowledgedSafetyChecks:
        kotlin.collections.List<ComputerToolCallSafetyCheck>? =
        null,

    /* The status of the message input. One of `in_progress`, `completed`, or `incomplete`. Populated when input items are returned via API.  */
    @Json(name = "status") val status: ComputerToolCallOutput.Status? = null,
) {

    /**
     * The type of the computer tool call output. Always `computer_call_output`.
     *
     * Values: computer_call_output
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "computer_call_output")
        computer_call_output("computer_call_output")
    }

    /**
     * The status of the message input. One of `in_progress`, `completed`, or
     * `incomplete`. Populated when input items are returned via API.
     *
     * Values: in_progress,completed,incomplete
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "in_progress") in_progress("in_progress"),
        @Json(name = "completed") completed("completed"),
        @Json(name = "incomplete") incomplete("incomplete"),
    }
}
