/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A filter used to compare a specified attribute key to a given value using a
 * defined comparison operation.
 *
 * @param type Specifies the comparison operator: `eq`, `ne`, `gt`, `gte`, `lt`,
 *   `lte`. - `eq`: equals - `ne`: not equal - `gt`: greater than - `gte`:
 *   greater than or equal - `lt`: less than - `lte`: less than or equal
 * @param key The key to compare against the value.
 * @param `value`
 */
data class ComparisonFilter(

    /* Specifies the comparison operator: `eq`, `ne`, `gt`, `gte`, `lt`, `lte`. - `eq`: equals - `ne`: not equal - `gt`: greater than - `gte`: greater than or equal - `lt`: less than - `lte`: less than or equal  */
    @Json(name = "type") val type: ComparisonFilter.Type = Type.eq,

    /* The key to compare against the value. */
    @Json(name = "key") val key: kotlin.String,
    @Json(name = "value") val `value`: ComparisonFilterValue,
) {

    /**
     * Specifies the comparison operator: `eq`, `ne`, `gt`, `gte`, `lt`,
     * `lte`. - `eq`: equals - `ne`: not equal - `gt`: greater than - `gte`:
     * greater than or equal - `lt`: less than - `lte`: less than or equal
     *
     * Values: eq,ne,gt,gte,lt,lte
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "eq") eq("eq"),
        @Json(name = "ne") ne("ne"),
        @Json(name = "gt") gt("gt"),
        @Json(name = "gte") gte("gte"),
        @Json(name = "lt") lt("lt"),
        @Json(name = "lte") lte("lte"),
    }
}
