/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Parameters for audio output. Required when audio output is requested with
 * `modalities: [\"audio\"]`. [Learn more](/docs/guides/audio).
 *
 * @param voice
 * @param format Specifies the output audio format. Must be one of `wav`, `mp3`,
 *   `flac`, `opus`, or `pcm16`.
 */
data class CreateChatCompletionRequestAllOfAudio(
    @Json(name = "voice") val voice: VoiceIdsShared,

    /* Specifies the output audio format. Must be one of `wav`, `mp3`, `flac`, `opus`, or `pcm16`.  */
    @Json(name = "format")
    val format: CreateChatCompletionRequestAllOfAudio.Format,
) {

    /**
     * Specifies the output audio format. Must be one of `wav`, `mp3`, `flac`,
     * `opus`, or `pcm16`.
     *
     * Values: wav,mp3,flac,opus,pcm16
     */
    @JsonClass(generateAdapter = false)
    enum class Format(val value: kotlin.String) {
        @Json(name = "wav") wav("wav"),
        @Json(name = "mp3") mp3("mp3"),
        @Json(name = "flac") flac("flac"),
        @Json(name = "opus") opus("opus"),
        @Json(name = "pcm16") pcm16("pcm16"),
    }
}
