/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

/**  */
// openai-openapi-kotlin change begin
class CreateThreadRequestToolResourcesFileSearch() {}
// openai-openapi-kotlin change end
