/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

/**
 * Text, image, or file inputs to the model, used to generate a response. Learn
 * more: - [Text inputs and outputs](/docs/guides/text) - [Image
 * inputs](/docs/guides/images) - [File
 * inputs](/docs/guides/pdf-files) - [Conversation
 * state](/docs/guides/conversation-state) - [Function calling](/docs/guides/function-calling)
 */
class CreateResponseAllOfInput() {}
