/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json

/**
 * The hyperparameters used for the fine-tuning job. This value is now
 * deprecated in favor of `method`, and should be passed in under the `method`
 * parameter.
 *
 * @param batchSize
 * @param learningRateMultiplier
 * @param nEpochs
 */
@Deprecated(message = "This schema is deprecated.")
data class CreateFineTuningJobRequestHyperparameters(
    @Json(name = "batch_size")
    val batchSize: CreateFineTuningJobRequestHyperparametersBatchSize? = null,
    @Json(name = "learning_rate_multiplier")
    val learningRateMultiplier:
        CreateFineTuningJobRequestHyperparametersLearningRateMultiplier? =
        null,
    @Json(name = "n_epochs")
    val nEpochs: CreateFineTuningJobRequestHyperparametersNEpochs? = null,
) {}
