/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json

/**
 * @param input
 * @param model
 */
data class CreateModerationRequest(
    @Json(name = "input") val input: CreateModerationRequestInput,
    @Json(name = "model") val model: CreateModerationRequestModel? = null,
) {}
