/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json

/**
 * @param fileIds A list of [File](/docs/api-reference/files) IDs that the
 *   vector store should use. Useful for tools like `file_search` that can
 *   access files.
 * @param chunkingStrategy
 * @param attributes Set of 16 key-value pairs that can be attached to an
 *   object. This can be useful for storing additional information about the
 *   object in a structured format, and querying for objects via API or the
 *   dashboard. Keys are strings with a maximum length of 64 characters. Values
 *   are strings with a maximum length of 512 characters, booleans, or numbers.
 */
data class CreateVectorStoreFileBatchRequest(

    /* A list of [File](/docs/api-reference/files) IDs that the vector store should use. Useful for tools like `file_search` that can access files. */
    @Json(name = "file_ids")
    val fileIds: kotlin.collections.List<kotlin.String>,
    @Json(name = "chunking_strategy")
    val chunkingStrategy: ChunkingStrategyRequestParam? = null,

    /* Set of 16 key-value pairs that can be attached to an object. This can be  useful for storing additional information about the object in a structured  format, and querying for objects via API or the dashboard. Keys are strings  with a maximum length of 64 characters. Values are strings with a maximum  length of 512 characters, booleans, or numbers.  */
    @Json(name = "attributes")
    val attributes:
        kotlin.collections.Map<kotlin.String, VectorStoreFileAttributesValue>? =
        null,
) {}
