/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Configuration for a [Predicted Output](/docs/guides/predicted-outputs), which can greatly improve response times when large parts of the model response are known ahead of time. This is most common when you are regenerating a file with only minor changes to most of the content. 
 *
 * @param type The type of the predicted content you want to provide. This type is currently always `content`. 
 * @param content 
 */


data class CreateChatCompletionRequestPrediction (

    /* The type of the predicted content you want to provide. This type is currently always `content`.  */
    @Json(name = "type")
    val type: CreateChatCompletionRequestPrediction.Type,

    @Json(name = "content")
    val content: PredictionContentContent

) {

    /**
     * The type of the predicted content you want to provide. This type is currently always `content`. 
     *
     * Values: content
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "content") content("content");
    }

}

