/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * An object specifying the format that the model must output. Setting to `{
 * \"type\": \"json_schema\", \"json_schema\": {...} }` enables Structured
 * Outputs which ensures the model will match your supplied JSON schema. Learn
 * more in the [Structured Outputs guide](/docs/guides/structured-outputs).
 * Setting to `{ \"type\": \"json_object\" }` enables the older JSON mode, which
 * ensures the message the model generates is valid JSON. Using `json_schema` is
 * preferred for models that support it.
 *
 * @param type The type of response format being defined. Always `text`.
 * @param jsonSchema
 */
data class CreateChatCompletionRequestAllOfResponseFormat(

    /* The type of response format being defined. Always `text`. */
    @Json(name = "type")
    val type: CreateChatCompletionRequestAllOfResponseFormat.Type,
    @Json(name = "json_schema") val jsonSchema: JSONSchema,
) {

    /**
     * The type of response format being defined. Always `text`.
     *
     * Values: text,json_schema,json_object
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "text") text("text"),
        @Json(name = "json_schema") json_schema("json_schema"),
        @Json(name = "json_object") json_object("json_object"),
    }
}
