/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param code 
 * @param message 
 */


data class DefaultProjectErrorResponse (

    @Json(name = "code")
    val code: kotlin.Int,

    @Json(name = "message")
    val message: kotlin.String

) {


}

