/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @param id The ID of the fine-tuned model checkpoint permission that was
 *   deleted.
 * @param `object` The object type, which is always \"checkpoint.permission\".
 * @param deleted Whether the fine-tuned model checkpoint permission was
 *   successfully deleted.
 */
data class DeleteFineTuningCheckpointPermissionResponse(

    /* The ID of the fine-tuned model checkpoint permission that was deleted. */
    @Json(name = "id") val id: kotlin.String,

    /* The object type, which is always \"checkpoint.permission\". */
    @Json(name = "object")
    val `object`: DeleteFineTuningCheckpointPermissionResponse.`Object`,

    /* Whether the fine-tuned model checkpoint permission was successfully deleted. */
    @Json(name = "deleted") val deleted: kotlin.Boolean,
) {

    /**
     * The object type, which is always \"checkpoint.permission\".
     *
     * Values: checkpointPeriodPermission
     */
    @JsonClass(generateAdapter = false)
    enum class `Object`(val value: kotlin.String) {
        @Json(name = "checkpoint.permission")
        checkpointPeriodPermission("checkpoint.permission")
    }
}
