/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A drag action.
 *
 * @param type Specifies the event type. For a drag action, this property is
 *   always set to `drag`.
 * @param path An array of coordinates representing the path of the drag action.
 *   Coordinates will appear as an array of objects, eg ``` [ { x: 100, y: 200
 *   }, { x: 200, y: 300 } ] ```
 */
data class Drag(

    /* Specifies the event type. For a drag action, this property is  always set to `drag`.  */
    @Json(name = "type") val type: Drag.Type = Type.drag,

    /* An array of coordinates representing the path of the drag action. Coordinates will appear as an array of objects, eg ``` [   { x: 100, y: 200 },   { x: 200, y: 300 } ] ```  */
    @Json(name = "path") val path: kotlin.collections.List<Coordinate>,
) {

    /**
     * Specifies the event type. For a drag action, this property is always set
     * to `drag`.
     *
     * Values: drag
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "drag") drag("drag")
    }
}
