/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A message input to the model with a role indicating instruction following
 * hierarchy. Instructions given with the `developer` or `system` role take
 * precedence over instructions given with the `user` role. Messages with the
 * `assistant` role are presumed to have been generated by the model in previous
 * interactions.
 *
 * @param role The role of the message input. One of `user`, `assistant`,
 *   `system`, or `developer`.
 * @param content
 * @param type The type of the message input. Always `message`.
 */
data class EasyInputMessage(

    /* The role of the message input. One of `user`, `assistant`, `system`, or `developer`.  */
    @Json(name = "role") val role: EasyInputMessage.Role,
    @Json(name = "content") val content: EasyInputMessageContent,

    /* The type of the message input. Always `message`.  */
    @Json(name = "type") val type: EasyInputMessage.Type? = null,
) {

    /**
     * The role of the message input. One of `user`, `assistant`, `system`, or
     * `developer`.
     *
     * Values: user,assistant,system,developer
     */
    @JsonClass(generateAdapter = false)
    enum class Role(val value: kotlin.String) {
        @Json(name = "user") user("user"),
        @Json(name = "assistant") assistant("assistant"),
        @Json(name = "system") system("system"),
        @Json(name = "developer") developer("developer"),
    }

    /**
     * The type of the message input. Always `message`.
     *
     * Values: message
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "message") message("message")
    }
}
