/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A citation to a file.
 *
 * @param type The type of the file citation. Always `file_citation`.
 * @param index The index of the file in the list of files.
 * @param fileId The ID of the file.
 */
data class FileCitation(

    /* The type of the file citation. Always `file_citation`.  */
    @Json(name = "type") val type: FileCitation.Type,

    /* The index of the file in the list of files.  */
    @Json(name = "index") val index: kotlin.Int,

    /* The ID of the file.  */
    @Json(name = "file_id") val fileId: kotlin.String,
) {

    /**
     * The type of the file citation. Always `file_citation`.
     *
     * Values: file_citation
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "file_citation") file_citation("file_citation")
    }
}
