/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The ranker to use for the file search. If not specified will use the `auto`
 * ranker.
 *
 * Values: auto,default_2024_08_21
 */
@JsonClass(generateAdapter = false)
enum class FileSearchRanker(val value: kotlin.String) {

    @Json(name = "auto") auto("auto"),
    @Json(name = "default_2024_08_21") default_2024_08_21("default_2024_08_21");

    /**
     * Override [toString()] to avoid using the enum variable name as the value,
     * and instead use the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different,
     * and ensures that the client sends the correct enum values to the server
     * always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null
         * otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? =
            if (data is FileSearchRanker) "$data" else null

        /** Returns a valid [FileSearchRanker] for [data], null otherwise. */
        fun decode(data: kotlin.Any?): FileSearchRanker? =
            data?.let {
                val normalizedData = "$it".lowercase()
                values().firstOrNull { value ->
                    it == value || normalizedData == "$value".lowercase()
                }
            }
    }
}
