/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A path to a file.
 *
 * @param type The type of the file path. Always `file_path`.
 * @param fileId The ID of the file.
 * @param index The index of the file in the list of files.
 */
data class FilePath(

    /* The type of the file path. Always `file_path`.  */
    @Json(name = "type") val type: FilePath.Type,

    /* The ID of the file.  */
    @Json(name = "file_id") val fileId: kotlin.String,

    /* The index of the file in the list of files.  */
    @Json(name = "index") val index: kotlin.Int,
) {

    /**
     * The type of the file path. Always `file_path`.
     *
     * Values: file_path
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "file_path") file_path("file_path")
    }
}
