/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The results of a file search tool call. See the
 * [file search guide](/docs/guides/tools-file-search) for more information.
 *
 * @param id The unique ID of the file search tool call.
 * @param type The type of the file search tool call. Always `file_search_call`.
 * @param status The status of the file search tool call. One of `in_progress`,
 *   `searching`, `incomplete` or `failed`,
 * @param queries The queries used to search for files.
 * @param results The results of the file search tool call.
 */
data class FileSearchToolCall(

    /* The unique ID of the file search tool call.  */
    @Json(name = "id") val id: kotlin.String,

    /* The type of the file search tool call. Always `file_search_call`.  */
    @Json(name = "type") val type: FileSearchToolCall.Type,

    /* The status of the file search tool call. One of `in_progress`,  `searching`, `incomplete` or `failed`,  */
    @Json(name = "status") val status: FileSearchToolCall.Status,

    /* The queries used to search for files.  */
    @Json(name = "queries") val queries: kotlin.collections.List<kotlin.String>,

    /* The results of the file search tool call.  */
    @Json(name = "results")
    val results: kotlin.collections.List<FileSearchToolCallResultsInner>? = null,
) {

    /**
     * The type of the file search tool call. Always `file_search_call`.
     *
     * Values: file_search_call
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "file_search_call") file_search_call("file_search_call")
    }

    /**
     * The status of the file search tool call. One of `in_progress`,
     * `searching`, `incomplete` or `failed`,
     *
     * Values: in_progress,searching,completed,incomplete,failed
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "in_progress") in_progress("in_progress"),
        @Json(name = "searching") searching("searching"),
        @Json(name = "completed") completed("completed"),
        @Json(name = "incomplete") incomplete("incomplete"),
        @Json(name = "failed") failed("failed"),
    }
}
