/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models

import com.openai.models.FineTuneSupervisedMethodHyperparameters

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Configuration for the supervised fine-tuning method.
 *
 * @param hyperparameters 
 */


data class FineTuneSupervisedMethod (

    @Json(name = "hyperparameters")
    val hyperparameters: FineTuneSupervisedMethodHyperparameters? = null

) {


}

