/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The `checkpoint.permission` object represents a permission for a fine-tuned
 * model checkpoint.
 *
 * @param id The permission identifier, which can be referenced in the API
 *   endpoints.
 * @param createdAt The Unix timestamp (in seconds) for when the permission was
 *   created.
 * @param projectId The project identifier that the permission is for.
 * @param `object` The object type, which is always \"checkpoint.permission\".
 */
data class FineTuningCheckpointPermission(

    /* The permission identifier, which can be referenced in the API endpoints. */
    @Json(name = "id") val id: kotlin.String,

    /* The Unix timestamp (in seconds) for when the permission was created. */
    @Json(name = "created_at") val createdAt: kotlin.Int,

    /* The project identifier that the permission is for. */
    @Json(name = "project_id") val projectId: kotlin.String,

    /* The object type, which is always \"checkpoint.permission\". */
    @Json(name = "object") val `object`: FineTuningCheckpointPermission.`Object`,
) {

    /**
     * The object type, which is always \"checkpoint.permission\".
     *
     * Values: checkpointPeriodPermission
     */
    @JsonClass(generateAdapter = false)
    enum class `Object`(val value: kotlin.String) {
        @Json(name = "checkpoint.permission")
        checkpointPeriodPermission("checkpoint.permission")
    }
}
