/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models

import com.openai.models.CreateFineTuningJobRequestHyperparametersBatchSize
import com.openai.models.CreateFineTuningJobRequestHyperparametersLearningRateMultiplier
import com.openai.models.CreateFineTuningJobRequestHyperparametersNEpochs

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The hyperparameters used for the fine-tuning job. This value will only be returned when running `supervised` jobs.
 *
 * @param batchSize 
 * @param learningRateMultiplier 
 * @param nEpochs 
 */


data class FineTuningJobHyperparameters (

    @Json(name = "batch_size")
    val batchSize: CreateFineTuningJobRequestHyperparametersBatchSize? = null,

    @Json(name = "learning_rate_multiplier")
    val learningRateMultiplier: CreateFineTuningJobRequestHyperparametersLearningRateMultiplier? = null,

    @Json(name = "n_epochs")
    val nEpochs: CreateFineTuningJobRequestHyperparametersNEpochs? = null

) {


}

