/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @param id The unique ID of the function call tool output.
 * @param type The type of the function tool call output. Always
 *   `function_call_output`.
 * @param callId The unique ID of the function tool call generated by the model.
 * @param output A JSON string of the output of the function tool call.
 * @param status The status of the item. One of `in_progress`, `completed`, or
 *   `incomplete`. Populated when items are returned via API.
 */
data class FunctionToolCallOutputResource(

    /* The unique ID of the function call tool output.  */
    @Json(name = "id") val id: kotlin.String,

    /* The type of the function tool call output. Always `function_call_output`.  */
    @Json(name = "type") val type: FunctionToolCallOutputResource.Type,

    /* The unique ID of the function tool call generated by the model.  */
    @Json(name = "call_id") val callId: kotlin.String,

    /* A JSON string of the output of the function tool call.  */
    @Json(name = "output") val output: kotlin.String,

    /* The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.  */
    @Json(name = "status")
    val status: FunctionToolCallOutputResource.Status? = null,
) {

    /**
     * The type of the function tool call output. Always `function_call_output`.
     *
     * Values: function_call_output
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "function_call_output")
        function_call_output("function_call_output")
    }

    /**
     * The status of the item. One of `in_progress`, `completed`, or
     * `incomplete`. Populated when items are returned via API.
     *
     * Values: in_progress,completed,incomplete
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "in_progress") in_progress("in_progress"),
        @Json(name = "completed") completed("completed"),
        @Json(name = "incomplete") incomplete("incomplete"),
    }
}
