/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A text input to the model.
 *
 * @param type The type of the input item. Always `input_text`.
 * @param text The text input to the model.
 */
data class InputText(

    /* The type of the input item. Always `input_text`.  */
    @Json(name = "type") val type: InputText.Type,

    /* The text input to the model.  */
    @Json(name = "text") val text: kotlin.String,
) {

    /**
     * The type of the input item. Always `input_text`.
     *
     * Values: input_text
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "input_text") input_text("input_text")
    }
}
