/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A file input to the model.
 *
 * @param type The type of the input item. Always `input_file`.
 * @param fileId The ID of the file to be sent to the model.
 * @param filename The name of the file to be sent to the model.
 * @param fileData The content of the file to be sent to the model.
 */
data class InputFile(

    /* The type of the input item. Always `input_file`.  */
    @Json(name = "type") val type: InputFile.Type,

    /* The ID of the file to be sent to the model.  */
    @Json(name = "file_id") val fileId: kotlin.String? = null,

    /* The name of the file to be sent to the model.  */
    @Json(name = "filename") val filename: kotlin.String? = null,

    /* The content of the file to be sent to the model.  */
    @Json(name = "file_data") val fileData: kotlin.String? = null,
) {

    /**
     * The type of the input item. Always `input_file`.
     *
     * Values: input_file
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "input_file") input_file("input_file")
    }
}
