/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @param type The type of the input item. Always `input_text`.
 * @param text The text input to the model.
 * @param detail The detail level of the image to be sent to the model. One of
 *   `high`, `low`, or `auto`. Defaults to `auto`.
 * @param imageUrl The URL of the image to be sent to the model. A fully
 *   qualified URL or base64 encoded image in a data URL.
 * @param fileId The ID of the file to be sent to the model.
 * @param filename The name of the file to be sent to the model.
 * @param fileData The content of the file to be sent to the model.
 */
data class InputContent(

    /* The type of the input item. Always `input_text`.  */
    @Json(name = "type") val type: InputContent.Type,

    /* The text input to the model.  */
    @Json(name = "text") val text: kotlin.String,

    /* The detail level of the image to be sent to the model. One of `high`, `low`, or `auto`. Defaults to `auto`.  */
    @Json(name = "detail") val detail: InputContent.Detail = Detail.auto,

    /* The URL of the image to be sent to the model. A fully qualified URL or base64 encoded image in a data URL.  */
    @Json(name = "image_url") val imageUrl: kotlin.String? = null,

    /* The ID of the file to be sent to the model.  */
    @Json(name = "file_id") val fileId: kotlin.String? = null,

    /* The name of the file to be sent to the model.  */
    @Json(name = "filename") val filename: kotlin.String? = null,

    /* The content of the file to be sent to the model.  */
    @Json(name = "file_data") val fileData: kotlin.String? = null,
) {

    /**
     * The type of the input item. Always `input_text`.
     *
     * Values: input_text,input_image,input_file
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "input_text") input_text("input_text"),
        @Json(name = "input_image") input_image("input_image"),
        @Json(name = "input_file") input_file("input_file"),
    }

    /**
     * The detail level of the image to be sent to the model. One of `high`,
     * `low`, or `auto`. Defaults to `auto`.
     *
     * Values: high,low,auto
     */
    @JsonClass(generateAdapter = false)
    enum class Detail(val value: kotlin.String) {
        @Json(name = "high") high("high"),
        @Json(name = "low") low("low"),
        @Json(name = "auto") auto("auto"),
    }
}
