/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @param role The role of the message input. One of `user`, `system`, or
 *   `developer`.
 * @param content A list of one or many input items to the model, containing
 *   different content types.
 * @param id The unique ID of the message input.
 * @param type The type of the message input. Always set to `message`.
 * @param status The status of item. One of `in_progress`, `completed`, or
 *   `incomplete`. Populated when items are returned via API.
 */
data class InputMessageResource(

    /* The role of the message input. One of `user`, `system`, or `developer`.  */
    @Json(name = "role") val role: InputMessageResource.Role,

    /* A list of one or many input items to the model, containing different content  types.  */
    @Json(name = "content") val content: kotlin.collections.List<InputContent>,

    /* The unique ID of the message input.  */
    @Json(name = "id") val id: kotlin.String,

    /* The type of the message input. Always set to `message`.  */
    @Json(name = "type") val type: InputMessageResource.Type? = null,

    /* The status of item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.  */
    @Json(name = "status") val status: InputMessageResource.Status? = null,
) {

    /**
     * The role of the message input. One of `user`, `system`, or `developer`.
     *
     * Values: user,system,developer
     */
    @JsonClass(generateAdapter = false)
    enum class Role(val value: kotlin.String) {
        @Json(name = "user") user("user"),
        @Json(name = "system") system("system"),
        @Json(name = "developer") developer("developer"),
    }

    /**
     * The type of the message input. Always set to `message`.
     *
     * Values: message
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "message") message("message")
    }

    /**
     * The status of item. One of `in_progress`, `completed`, or `incomplete`.
     * Populated when items are returned via API.
     *
     * Values: in_progress,completed,incomplete
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "in_progress") in_progress("in_progress"),
        @Json(name = "completed") completed("completed"),
        @Json(name = "incomplete") incomplete("incomplete"),
    }
}
