/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json

/**
 * @param token The token that was used to generate the log probability.
 * @param logprob The log probability of the token.
 * @param bytes The bytes that were used to generate the log probability.
 * @param topLogprobs
 */
data class LogProb(

    /* The token that was used to generate the log probability.  */
    @Json(name = "token") val token: kotlin.String,

    /* The log probability of the token.  */
    @Json(name = "logprob") val logprob: java.math.BigDecimal,

    /* The bytes that were used to generate the log probability.  */
    @Json(name = "bytes") val bytes: kotlin.collections.List<kotlin.Int>,
    @Json(name = "top_logprobs")
    val topLogprobs: kotlin.collections.List<LogProbProperties>? = null,
) {}
