/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models

import com.openai.models.MessageContentImageFileObject
import com.openai.models.MessageContentImageFileObjectImageFile
import com.openai.models.MessageContentImageUrlObject
import com.openai.models.MessageContentImageUrlObjectImageUrl
import com.openai.models.MessageContentRefusalObject
import com.openai.models.MessageContentTextObject
import com.openai.models.MessageContentTextObjectText

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type Always `image_file`.
 * @param imageFile 
 * @param imageUrl 
 * @param text 
 * @param refusal 
 */


data class MessageObjectContentInner (

    /* Always `image_file`. */
    @Json(name = "type")
    val type: MessageObjectContentInner.Type,

    @Json(name = "image_file")
    val imageFile: MessageContentImageFileObjectImageFile,

    @Json(name = "image_url")
    val imageUrl: MessageContentImageUrlObjectImageUrl,

    @Json(name = "text")
    val text: MessageContentTextObjectText,

    @Json(name = "refusal")
    val refusal: kotlin.String

) {

    /**
     * Always `image_file`.
     *
     * Values: image_file,image_url,text,refusal
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "image_file") image_file("image_file"),
        @Json(name = "image_url") image_url("image_url"),
        @Json(name = "text") text("text"),
        @Json(name = "refusal") refusal("refusal");
    }

}

