/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A mouse move action.
 *
 * @param type Specifies the event type. For a move action, this property is
 *   always set to `move`.
 * @param x The x-coordinate to move to.
 * @param y The y-coordinate to move to.
 */
data class Move(

    /* Specifies the event type. For a move action, this property is  always set to `move`.  */
    @Json(name = "type") val type: Move.Type = Type.move,

    /* The x-coordinate to move to.  */
    @Json(name = "x") val x: kotlin.Int,

    /* The y-coordinate to move to.  */
    @Json(name = "y") val y: kotlin.Int,
) {

    /**
     * Specifies the event type. For a move action, this property is always set
     * to `move`.
     *
     * Values: move
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "move") move("move")
    }
}
