/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * An output message from the model.
 *
 * @param id The unique ID of the output message.
 * @param type The type of the output message. Always `message`.
 * @param role The role of the output message. Always `assistant`.
 * @param content The content of the output message.
 * @param status The status of the message input. One of `in_progress`,
 *   `completed`, or `incomplete`. Populated when input items are returned via
 *   API.
 */
data class OutputMessage(

    /* The unique ID of the output message.  */
    @Json(name = "id") val id: kotlin.String,

    /* The type of the output message. Always `message`.  */
    @Json(name = "type") val type: OutputMessage.Type,

    /* The role of the output message. Always `assistant`.  */
    @Json(name = "role") val role: OutputMessage.Role,

    /* The content of the output message.  */
    @Json(name = "content") val content: kotlin.collections.List<OutputContent>,

    /* The status of the message input. One of `in_progress`, `completed`, or `incomplete`. Populated when input items are returned via API.  */
    @Json(name = "status") val status: OutputMessage.Status,
) {

    /**
     * The type of the output message. Always `message`.
     *
     * Values: message
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "message") message("message")
    }

    /**
     * The role of the output message. Always `assistant`.
     *
     * Values: assistant
     */
    @JsonClass(generateAdapter = false)
    enum class Role(val value: kotlin.String) {
        @Json(name = "assistant") assistant("assistant")
    }

    /**
     * The status of the message input. One of `in_progress`, `completed`, or
     * `incomplete`. Populated when input items are returned via API.
     *
     * Values: in_progress,completed,incomplete
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "in_progress") in_progress("in_progress"),
        @Json(name = "completed") completed("completed"),
        @Json(name = "incomplete") incomplete("incomplete"),
    }
}
