/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * An audio output from the model.
 *
 * @param type The type of the output audio. Always `output_audio`.
 * @param `data` Base64-encoded audio data from the model.
 * @param transcript The transcript of the audio data from the model.
 */
data class OutputAudio(

    /* The type of the output audio. Always `output_audio`.  */
    @Json(name = "type") val type: OutputAudio.Type,

    /* Base64-encoded audio data from the model.  */
    @Json(name = "data") val `data`: kotlin.String,

    /* The transcript of the audio data from the model.  */
    @Json(name = "transcript") val transcript: kotlin.String,
) {

    /**
     * The type of the output audio. Always `output_audio`.
     *
     * Values: output_audio
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "output_audio") output_audio("output_audio")
    }
}
