/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @param id The unique identifier of the reasoning content.
 * @param type The type of the output message. Always `message`.
 * @param role The role of the output message. Always `assistant`.
 * @param content The content of the output message.
 * @param status The status of the item. One of `in_progress`, `completed`, or
 *   `incomplete`. Populated when items are returned via API.
 * @param queries The queries used to search for files.
 * @param callId An identifier used when responding to the tool call with
 *   output.
 * @param name The name of the function to run.
 * @param arguments A JSON string of the arguments to pass to the function.
 * @param action
 * @param pendingSafetyChecks The pending safety checks for the computer call.
 * @param summary Reasoning text contents.
 * @param results The results of the file search tool call.
 */
interface OutputItem {

    /* The unique identifier of the reasoning content.  */
    @Json(name = "id") val id: kotlin.String
    /* The type of the output message. Always `message`.  */
    @Json(name = "type") val type: OutputItem.Type
    /* The role of the output message. Always `assistant`.  */
    @Json(name = "role") val role: OutputItem.Role
    /* The content of the output message.  */
    @Json(name = "content") val content: kotlin.collections.List<OutputContent>
    /* The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.  */
    @Json(name = "status") val status: OutputItem.Status
    /* The queries used to search for files.  */
    @Json(name = "queries") val queries: kotlin.collections.List<kotlin.String>
    /* An identifier used when responding to the tool call with output.  */
    @Json(name = "call_id") val callId: kotlin.String
    /* The name of the function to run.  */
    @Json(name = "name") val name: kotlin.String
    /* A JSON string of the arguments to pass to the function.  */
    @Json(name = "arguments") val arguments: kotlin.String
    @Json(name = "action") val action: ComputerAction
    /* The pending safety checks for the computer call.  */
    @Json(name = "pending_safety_checks")
    val pendingSafetyChecks:
        kotlin.collections.List<ComputerToolCallSafetyCheck>
    /* Reasoning text contents.  */
    @Json(name = "summary")
    val summary: kotlin.collections.List<ReasoningItemSummaryInner>
    /* The results of the file search tool call.  */
    @Json(name = "results")
    val results: kotlin.collections.List<FileSearchToolCallResultsInner>?

    /**
     * The type of the output message. Always `message`.
     *
     * Values:
     * message,file_search_call,function_call,web_search_call,computer_call,reasoning
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "message") message("message"),
        @Json(name = "file_search_call") file_search_call("file_search_call"),
        @Json(name = "function_call") function_call("function_call"),
        @Json(name = "web_search_call") web_search_call("web_search_call"),
        @Json(name = "computer_call") computer_call("computer_call"),
        @Json(name = "reasoning") reasoning("reasoning"),
    }

    /**
     * The role of the output message. Always `assistant`.
     *
     * Values: assistant
     */
    @JsonClass(generateAdapter = false)
    enum class Role(val value: kotlin.String) {
        @Json(name = "assistant") assistant("assistant")
    }

    /**
     * The status of the item. One of `in_progress`, `completed`, or
     * `incomplete`. Populated when items are returned via API.
     *
     * Values: in_progress,completed,incomplete
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "in_progress") in_progress("in_progress"),
        @Json(name = "completed") completed("completed"),
        @Json(name = "incomplete") incomplete("incomplete"),
    }
}
