/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Send this event to update a transcription session.
 *
 * @param type The event type, must be `transcription_session.update`.
 * @param session
 * @param eventId Optional client-generated ID used to identify this event.
 */
data class RealtimeClientEventTranscriptionSessionUpdate(

    /* The event type, must be `transcription_session.update`. */
    @Json(name = "type")
    // openai-openapi-kotlin changes begin
    val type: RealtimeClientEventTranscriptionSessionUpdate.Type =
        RealtimeClientEventTranscriptionSessionUpdate.Type
            .transcription_sessionPeriodUpdate,
    // openai-openapi-kotlin changes end
    @Json(name = "session")
    val session: RealtimeTranscriptionSessionCreateRequest,

    /* Optional client-generated ID used to identify this event. */
    @Json(name = "event_id") val eventId: kotlin.String? = null,
) {

    /**
     * The event type, must be `transcription_session.update`.
     *
     * Values: transcription_sessionPeriodUpdate
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "transcription_session.update")
        transcription_sessionPeriodUpdate("transcription_session.update")
    }
}
