/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.openai.infrastructure.SerializeNull
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Realtime session object configuration.
 *
 * @param modalities The set of modalities the model can respond with. To
 *   disable audio, set this to [\"text\"].
 * @param model The Realtime model used for this session.
 * @param instructions The default system instructions (i.e. system message)
 *   prepended to model calls. This field allows the client to guide the model
 *   on desired responses. The model can be instructed on response content and
 *   format, (e.g. \"be extremely succinct\", \"act friendly\", \"here are
 *   examples of good responses\") and on audio behavior (e.g. \"talk quickly\",
 *   \"inject emotion into your voice\", \"laugh frequently\"). The instructions
 *   are not guaranteed to be followed by the model, but they provide guidance
 *   to the model on the desired behavior. Note that the server sets default
 *   instructions which will be used if this field is not set and are visible in
 *   the `session.created` event at the start of the session.
 * @param voice
 * @param inputAudioFormat The format of input audio. Options are `pcm16`,
 *   `g711_ulaw`, or `g711_alaw`. For `pcm16`, input audio must be 16-bit PCM at
 *   a 24kHz sample rate, single channel (mono), and little-endian byte order.
 * @param outputAudioFormat The format of output audio. Options are `pcm16`,
 *   `g711_ulaw`, or `g711_alaw`. For `pcm16`, output audio is sampled at a rate
 *   of 24kHz.
 * @param inputAudioTranscription
 * @param turnDetection
 * @param inputAudioNoiseReduction
 * @param tools Tools (functions) available to the model.
 * @param toolChoice How the model chooses tools. Options are `auto`, `none`,
 *   `required`, or specify a function.
 * @param temperature Sampling temperature for the model, limited to [0.6, 1.2].
 *   For audio models a temperature of 0.8 is highly recommended for best
 *   performance.
 * @param maxResponseOutputTokens
 */
data class RealtimeSessionCreateRequest(

    /* The set of modalities the model can respond with. To disable audio, set this to [\"text\"].  */
    @Json(name = "modalities")
    val modalities:
        kotlin.collections.List<RealtimeSessionCreateRequest.Modalities>? =
        null,

    /* The Realtime model used for this session.  */
    // openai-openapi-kotlin changes begin
    @Json(name = "model") val model: RealtimeSession.Model? = null,
    // openai-openapi-kotlin changes end

    /* The default system instructions (i.e. system message) prepended to model  calls. This field allows the client to guide the model on desired  responses. The model can be instructed on response content and format,  (e.g. \"be extremely succinct\", \"act friendly\", \"here are examples of good  responses\") and on audio behavior (e.g. \"talk quickly\", \"inject emotion  into your voice\", \"laugh frequently\"). The instructions are not guaranteed  to be followed by the model, but they provide guidance to the model on the desired behavior.  Note that the server sets default instructions which will be used if this  field is not set and are visible in the `session.created` event at the  start of the session.  */
    @Json(name = "instructions") val instructions: kotlin.String? = null,
    @Json(name = "voice") val voice: VoiceIdsShared? = null,

    /* The format of input audio. Options are `pcm16`, `g711_ulaw`, or `g711_alaw`. For `pcm16`, input audio must be 16-bit PCM at a 24kHz sample rate,  single channel (mono), and little-endian byte order.  */
    @Json(name = "input_audio_format")
    val inputAudioFormat: RealtimeSessionCreateRequest.InputAudioFormat? =
        InputAudioFormat.pcm16,

    /* The format of output audio. Options are `pcm16`, `g711_ulaw`, or `g711_alaw`. For `pcm16`, output audio is sampled at a rate of 24kHz.  */
    @Json(name = "output_audio_format")
    val outputAudioFormat: RealtimeSessionCreateRequest.OutputAudioFormat? =
        OutputAudioFormat.pcm16,
    // openai-openapi-kotlin changes begin
    @SerializeNull
    // openai-openapi-kotlin changes end
    @Json(name = "input_audio_transcription")
    val inputAudioTranscription: RealtimeSessionInputAudioTranscription? = null,
    // openai-openapi-kotlin changes begin
    @SerializeNull
    // openai-openapi-kotlin changes end
    @Json(name = "turn_detection")
    val turnDetection: RealtimeSessionTurnDetection? = null,
    // openai-openapi-kotlin changes begin
    @SerializeNull
    // openai-openapi-kotlin changes end
    @Json(name = "input_audio_noise_reduction")
    val inputAudioNoiseReduction: RealtimeSessionInputAudioNoiseReduction? =
        null,

    /* Tools (functions) available to the model. */
    @Json(name = "tools")
    val tools:
        kotlin.collections.List<RealtimeResponseCreateParamsToolsInner>? =
        null,

    /* How the model chooses tools. Options are `auto`, `none`, `required`, or  specify a function.  */
    @Json(name = "tool_choice") val toolChoice: kotlin.String? = "auto",

    /* Sampling temperature for the model, limited to [0.6, 1.2]. For audio models a temperature of 0.8 is highly recommended for best performance.  */
    @Json(name = "temperature")
    val temperature: java.math.BigDecimal? = java.math.BigDecimal("0.8"),
    @Json(name = "max_response_output_tokens")
    val maxResponseOutputTokens:
        RealtimeResponseCreateParamsMaxResponseOutputTokens? =
        null,
) {

    /**
     * The set of modalities the model can respond with. To disable audio, set
     * this to [\"text\"].
     *
     * Values: text,audio
     */
    @JsonClass(generateAdapter = false)
    enum class Modalities(val value: kotlin.String) {
        @Json(name = "text") text("text"),
        @Json(name = "audio") audio("audio"),
    }

    // openai-openapi-kotlin changes begin
    // `enum class Model` moved to RealtimeSession.Model
    // openai-openapi-kotlin changes end

    /**
     * The format of input audio. Options are `pcm16`, `g711_ulaw`, or
     * `g711_alaw`. For `pcm16`, input audio must be 16-bit PCM at a 24kHz
     * sample rate, single channel (mono), and little-endian byte order.
     *
     * Values: pcm16,g711_ulaw,g711_alaw
     */
    @JsonClass(generateAdapter = false)
    enum class InputAudioFormat(val value: kotlin.String) {
        @Json(name = "pcm16") pcm16("pcm16"),
        @Json(name = "g711_ulaw") g711_ulaw("g711_ulaw"),
        @Json(name = "g711_alaw") g711_alaw("g711_alaw"),
    }

    /**
     * The format of output audio. Options are `pcm16`, `g711_ulaw`, or
     * `g711_alaw`. For `pcm16`, output audio is sampled at a rate of 24kHz.
     *
     * Values: pcm16,g711_ulaw,g711_alaw
     */
    @JsonClass(generateAdapter = false)
    enum class OutputAudioFormat(val value: kotlin.String) {
        @Json(name = "pcm16") pcm16("pcm16"),
        @Json(name = "g711_ulaw") g711_ulaw("g711_ulaw"),
        @Json(name = "g711_alaw") g711_alaw("g711_alaw"),
    }
}
