/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

/**
 * Maximum number of output tokens for a single assistant response, inclusive of
 * tool calls, that was used in this response.
 */
// openai-openapi-kotlin changes begin
typealias RealtimeResponseMaxOutputTokens =
    RealtimeSessionMaxResponseOutputTokens
// openai-openapi-kotlin changes end
