/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Realtime transcription session object configuration.
 *
 * @param modalities The set of modalities the model can respond with. To
 *   disable audio, set this to [\"text\"].
 * @param inputAudioFormat The format of input audio. Options are `pcm16`,
 *   `g711_ulaw`, or `g711_alaw`. For `pcm16`, input audio must be 16-bit PCM at
 *   a 24kHz sample rate, single channel (mono), and little-endian byte order.
 * @param inputAudioTranscription
 * @param turnDetection
 * @param inputAudioNoiseReduction
 * @param include The set of items to include in the transcription. Current
 *   available items are: - `item.input_audio_transcription.logprobs`
 */
data class RealtimeTranscriptionSessionCreateRequest(

    /* The set of modalities the model can respond with. To disable audio, set this to [\"text\"].  */
    @Json(name = "modalities")
    val modalities:
        kotlin.collections.List<
            RealtimeTranscriptionSessionCreateRequest.Modalities
        >? =
        null,

    /* The format of input audio. Options are `pcm16`, `g711_ulaw`, or `g711_alaw`. For `pcm16`, input audio must be 16-bit PCM at a 24kHz sample rate,  single channel (mono), and little-endian byte order.  */
    @Json(name = "input_audio_format")
    val inputAudioFormat:
        RealtimeTranscriptionSessionCreateRequest.InputAudioFormat? =
        InputAudioFormat.pcm16,
    @Json(name = "input_audio_transcription")
    val inputAudioTranscription:
        RealtimeTranscriptionSessionCreateRequestInputAudioTranscription? =
        null,
    @Json(name = "turn_detection")
    val turnDetection: RealtimeTranscriptionSessionCreateRequestTurnDetection? =
        null,
    @Json(name = "input_audio_noise_reduction")
    val inputAudioNoiseReduction: RealtimeSessionInputAudioNoiseReduction? =
        null,

    /* The set of items to include in the transcription. Current available items are: - `item.input_audio_transcription.logprobs`  */
    @Json(name = "include")
    val include: kotlin.collections.List<kotlin.String>? = null,
) {

    /**
     * The set of modalities the model can respond with. To disable audio, set
     * this to [\"text\"].
     *
     * Values: text,audio
     */
    @JsonClass(generateAdapter = false)
    enum class Modalities(val value: kotlin.String) {
        @Json(name = "text") text("text"),
        @Json(name = "audio") audio("audio"),
    }

    /**
     * The format of input audio. Options are `pcm16`, `g711_ulaw`, or
     * `g711_alaw`. For `pcm16`, input audio must be 16-bit PCM at a 24kHz
     * sample rate, single channel (mono), and little-endian byte order.
     *
     * Values: pcm16,g711_ulaw,g711_alaw
     */
    @JsonClass(generateAdapter = false)
    enum class InputAudioFormat(val value: kotlin.String) {
        @Json(name = "pcm16") pcm16("pcm16"),
        @Json(name = "g711_ulaw") g711_ulaw("g711_ulaw"),
        @Json(name = "g711_alaw") g711_alaw("g711_alaw"),
    }
}
