/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Returned when a conversation item is retrieved with
 * `conversation.item.retrieve`.
 *
 * @param eventId The unique ID of the server event.
 * @param type The event type, must be `conversation.item.retrieved`.
 * @param item
 */
data class RealtimeServerEventConversationItemRetrieved(

    /* The unique ID of the server event. */
    @Json(name = "event_id") val eventId: kotlin.String,

    /* The event type, must be `conversation.item.retrieved`. */
    @Json(name = "type")
    val type: RealtimeServerEventConversationItemRetrieved.Type,
    @Json(name = "item") val item: RealtimeConversationItem,
) {

    /**
     * The event type, must be `conversation.item.retrieved`.
     *
     * Values: conversationPeriodItemPeriodRetrieved
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "conversation.item.retrieved")
        conversationPeriodItemPeriodRetrieved("conversation.item.retrieved")
    }
}
