/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Send this event when you want to retrieve the server's representation of a
 * specific item in the conversation history. This is useful, for example, to
 * inspect user audio after noise cancellation and VAD. The server will respond
 * with a `conversation.item.retrieved` event, unless the item does not exist in
 * the conversation history, in which case the server will respond with an
 * error.
 *
 * @param type The event type, must be `conversation.item.retrieve`.
 * @param itemId The ID of the item to retrieve.
 * @param eventId Optional client-generated ID used to identify this event.
 */
data class RealtimeClientEventConversationItemRetrieve(

    /* The event type, must be `conversation.item.retrieve`. */
    @Json(name = "type")
    // openai-openapi-kotlin changes begin
    val type: RealtimeClientEventConversationItemRetrieve.Type =
        RealtimeClientEventConversationItemRetrieve.Type
            .conversationPeriodItemPeriodRetrieve,
    // openai-openapi-kotlin changes end

    /* The ID of the item to retrieve. */
    @Json(name = "item_id") val itemId: kotlin.String,

    /* Optional client-generated ID used to identify this event. */
    @Json(name = "event_id") val eventId: kotlin.String? = null,
) {

    /**
     * The event type, must be `conversation.item.retrieve`.
     *
     * Values: conversationPeriodItemPeriodRetrieve
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "conversation.item.retrieve")
        conversationPeriodItemPeriodRetrieve("conversation.item.retrieve")
    }
}
