/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Configuration for turn detection, ether Server VAD or Semantic VAD. This can
 * be set to `null` to turn off, in which case the client must manually trigger
 * model response. Server VAD means that the model will detect the start and end
 * of speech based on audio volume and respond at the end of user speech.
 * Semantic VAD is more advanced and uses a turn detection model (in conjuction
 * with VAD) to semantically estimate whether the user has finished speaking,
 * then dynamically sets a timeout based on this probability. For example, if
 * user audio trails off with \"uhhm\", the model will score a low probability
 * of turn end and wait longer for the user to continue speaking. This can be
 * useful for more natural conversations, but may have a higher latency.
 *
 * @param type Type of turn detection.
 * @param eagerness Used only for `semantic_vad` mode. The eagerness of the
 *   model to respond. `low` will wait longer for the user to continue speaking,
 *   `high` will respond more quickly. `auto` is the default and is equivalent
 *   to `medium`.
 * @param threshold Used only for `server_vad` mode. Activation threshold for
 *   VAD (0.0 to 1.0), this defaults to 0.5. A higher threshold will require
 *   louder audio to activate the model, and thus might perform better in noisy
 *   environments.
 * @param prefixPaddingMs Used only for `server_vad` mode. Amount of audio to
 *   include before the VAD detected speech (in milliseconds). Defaults to
 *   300ms.
 * @param silenceDurationMs Used only for `server_vad` mode. Duration of silence
 *   to detect speech stop (in milliseconds). Defaults to 500ms. With shorter
 *   values the model will respond more quickly, but may jump in on short pauses
 *   from the user.
 * @param createResponse Whether or not to automatically generate a response
 *   when a VAD stop event occurs. Not available for transcription sessions.
 * @param interruptResponse Whether or not to automatically interrupt any
 *   ongoing response with output to the default conversation (i.e.
 *   `conversation` of `auto`) when a VAD start event occurs. Not available for
 *   transcription sessions.
 */
data class RealtimeTranscriptionSessionCreateRequestTurnDetection(

    /* Type of turn detection.  */
    @Json(name = "type")
    val type: RealtimeTranscriptionSessionCreateRequestTurnDetection.Type? =
        Type.server_vad,

    /* Used only for `semantic_vad` mode. The eagerness of the model to respond. `low` will wait longer for the user to continue speaking, `high` will respond more quickly. `auto` is the default and is equivalent to `medium`.  */
    @Json(name = "eagerness")
    val eagerness:
        RealtimeTranscriptionSessionCreateRequestTurnDetection.Eagerness? =
        Eagerness.auto,

    /* Used only for `server_vad` mode. Activation threshold for VAD (0.0 to 1.0), this defaults to 0.5. A  higher threshold will require louder audio to activate the model, and  thus might perform better in noisy environments.  */
    @Json(name = "threshold") val threshold: java.math.BigDecimal? = null,

    /* Used only for `server_vad` mode. Amount of audio to include before the VAD detected speech (in  milliseconds). Defaults to 300ms.  */
    @Json(name = "prefix_padding_ms") val prefixPaddingMs: kotlin.Int? = null,

    /* Used only for `server_vad` mode. Duration of silence to detect speech stop (in milliseconds). Defaults  to 500ms. With shorter values the model will respond more quickly,  but may jump in on short pauses from the user.  */
    @Json(name = "silence_duration_ms")
    val silenceDurationMs: kotlin.Int? = null,

    /* Whether or not to automatically generate a response when a VAD stop event occurs. Not available for transcription sessions.  */
    @Json(name = "create_response") val createResponse: kotlin.Boolean? = true,

    /* Whether or not to automatically interrupt any ongoing response with output to the default conversation (i.e. `conversation` of `auto`) when a VAD start event occurs. Not available for transcription sessions.  */
    @Json(name = "interrupt_response")
    val interruptResponse: kotlin.Boolean? = true,
) {

    /**
     * Type of turn detection.
     *
     * Values: server_vad,semantic_vad
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "server_vad") server_vad("server_vad"),
        @Json(name = "semantic_vad") semantic_vad("semantic_vad"),
    }

    /**
     * Used only for `semantic_vad` mode. The eagerness of the model to respond.
     * `low` will wait longer for the user to continue speaking, `high` will
     * respond more quickly. `auto` is the default and is equivalent to
     * `medium`.
     *
     * Values: low,medium,high,auto
     */
    @JsonClass(generateAdapter = false)
    enum class Eagerness(val value: kotlin.String) {
        @Json(name = "low") low("low"),
        @Json(name = "medium") medium("medium"),
        @Json(name = "high") high("high"),
        @Json(name = "auto") auto("auto"),
    }
}
