/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Send this event to update the session’s default configuration. The client may
 * send this event at any time to update any field, except for `voice`. However,
 * note that once a session has been initialized with a particular `model`, it
 * can’t be changed to another model using `session.update`. When the server
 * receives a `session.update`, it will respond with a `session.updated` event
 * showing the full, effective configuration. Only the fields that are present
 * are updated. To clear a field like `instructions`, pass an empty string.
 *
 * @param type The event type, must be `session.update`.
 * @param session
 * @param eventId Optional client-generated ID used to identify this event.
 */
data class RealtimeClientEventSessionUpdate(

    /* The event type, must be `session.update`. */
    @Json(name = "type")
    // openai-openapi-kotlin changes begin
    val type: RealtimeClientEventSessionUpdate.Type =
        RealtimeClientEventSessionUpdate.Type.sessionPeriodUpdate,
    // openai-openapi-kotlin changes end
    @Json(name = "session") val session: RealtimeSessionCreateRequest,

    /* Optional client-generated ID used to identify this event. */
    @Json(name = "event_id") val eventId: kotlin.String? = null,
) {

    /**
     * The event type, must be `session.update`.
     *
     * Values: sessionPeriodUpdate
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "session.update") sessionPeriodUpdate("session.update")
    }
}
