/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Configuration for input audio transcription. The client can optionally set
 * the language and prompt for transcription, these offer additional guidance to
 * the transcription service.
 *
 * @param model The model to use for transcription, current options are
 *   `gpt-4o-transcribe`, `gpt-4o-mini-transcribe`, and `whisper-1`.
 * @param language The language of the input audio. Supplying the input language
 *   in [ISO-639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) (e.g.
 *   `en`) format will improve accuracy and latency.
 * @param prompt An optional text to guide the model's style or continue a
 *   previous audio segment. For `whisper-1`, the
 *   [prompt is a list of keywords](/docs/guides/speech-to-text#prompting). For
 *   `gpt-4o-transcribe` models, the prompt is a free text string, for example
 *   \"expect words related to technology\".
 */
data class RealtimeTranscriptionSessionCreateRequestInputAudioTranscription(

    /* The model to use for transcription, current options are `gpt-4o-transcribe`, `gpt-4o-mini-transcribe`, and `whisper-1`.  */
    @Json(name = "model")
    val model:
        RealtimeTranscriptionSessionCreateRequestInputAudioTranscription.Model? =
        null,

    /* The language of the input audio. Supplying the input language in [ISO-639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) (e.g. `en`) format will improve accuracy and latency.  */
    @Json(name = "language") val language: kotlin.String? = null,

    /* An optional text to guide the model's style or continue a previous audio segment. For `whisper-1`, the [prompt is a list of keywords](/docs/guides/speech-to-text#prompting). For `gpt-4o-transcribe` models, the prompt is a free text string, for example \"expect words related to technology\".  */
    @Json(name = "prompt") val prompt: kotlin.String? = null,
) {

    /**
     * The model to use for transcription, current options are
     * `gpt-4o-transcribe`, `gpt-4o-mini-transcribe`, and `whisper-1`.
     *
     * Values:
     * gptMinus4oMinusTranscribe,gptMinus4oMinusMiniMinusTranscribe,whisperMinus1
     */
    @JsonClass(generateAdapter = false)
    enum class Model(val value: kotlin.String) {
        @Json(name = "gpt-4o-transcribe")
        gptMinus4oMinusTranscribe("gpt-4o-transcribe"),
        @Json(name = "gpt-4o-mini-transcribe")
        gptMinus4oMinusMiniMinusTranscribe("gpt-4o-mini-transcribe"),
        @Json(name = "whisper-1") whisperMinus1("whisper-1"),
    }
}
