/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json

/**
 * Details about the output tokens used in the Response.
 *
 * @param textTokens The number of text tokens used in the Response.
 * @param audioTokens The number of audio tokens used in the Response.
 */
data class RealtimeResponseUsageOutputTokenDetails(

    /* The number of text tokens used in the Response. */
    @Json(name = "text_tokens") val textTokens: kotlin.Int? = null,

    /* The number of audio tokens used in the Response. */
    @Json(name = "audio_tokens") val audioTokens: kotlin.Int? = null,
) {}
