/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * **o-series models only** Configuration options for
 * [reasoning models](https://platform.openai.com/docs/guides/reasoning).
 *
 * @param effort
 * @param generateSummary **computer_use_preview only** A summary of the
 *   reasoning performed by the model. This can be useful for debugging and
 *   understanding the model's reasoning process. One of `concise` or
 *   `detailed`.
 */
data class Reasoning(
    @Json(name = "effort")
    val effort: ReasoningEffort? = ReasoningEffort.medium,

    /* **computer_use_preview only**  A summary of the reasoning performed by the model. This can be useful for debugging and understanding the model's reasoning process. One of `concise` or `detailed`.  */
    @Json(name = "generate_summary")
    val generateSummary: Reasoning.GenerateSummary? = null,
) {

    /**
     * **computer_use_preview only** A summary of the reasoning performed by the
     * model. This can be useful for debugging and understanding the model's
     * reasoning process. One of `concise` or `detailed`.
     *
     * Values: concise,detailed
     */
    @JsonClass(generateAdapter = false)
    enum class GenerateSummary(val value: kotlin.String) {
        @Json(name = "concise") concise("concise"),
        @Json(name = "detailed") detailed("detailed"),
    }
}
