/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A description of the chain of thought used by a reasoning model while
 * generating a response.
 *
 * @param type The type of the object. Always `reasoning`.
 * @param id The unique identifier of the reasoning content.
 * @param summary Reasoning text contents.
 * @param status The status of the item. One of `in_progress`, `completed`, or
 *   `incomplete`. Populated when items are returned via API.
 */
data class ReasoningItem(

    /* The type of the object. Always `reasoning`.  */
    @Json(name = "type") val type: ReasoningItem.Type,

    /* The unique identifier of the reasoning content.  */
    @Json(name = "id") val id: kotlin.String,

    /* Reasoning text contents.  */
    @Json(name = "summary")
    val summary: kotlin.collections.List<ReasoningItemSummaryInner>,

    /* The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.  */
    @Json(name = "status") val status: ReasoningItem.Status? = null,
) {

    /**
     * The type of the object. Always `reasoning`.
     *
     * Values: reasoning
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "reasoning") reasoning("reasoning")
    }

    /**
     * The status of the item. One of `in_progress`, `completed`, or
     * `incomplete`. Populated when items are returned via API.
     *
     * Values: in_progress,completed,incomplete
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "in_progress") in_progress("in_progress"),
        @Json(name = "completed") completed("completed"),
        @Json(name = "incomplete") incomplete("incomplete"),
    }
}
