/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @param type The type of the object. Always `summary_text`.
 * @param text A short summary of the reasoning used by the model when
 *   generating the response.
 */
data class ReasoningItemSummaryInner(

    /* The type of the object. Always `summary_text`.  */
    @Json(name = "type") val type: ReasoningItemSummaryInner.Type,

    /* A short summary of the reasoning used by the model when generating the response.  */
    @Json(name = "text") val text: kotlin.String,
) {

    /**
     * The type of the object. Always `summary_text`.
     *
     * Values: summary_text
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "summary_text") summary_text("summary_text")
    }
}
