/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A refusal from the model.
 *
 * @param type The type of the refusal. Always `refusal`.
 * @param refusal The refusal explanationfrom the model.
 */
data class Refusal(

    /* The type of the refusal. Always `refusal`.  */
    @Json(name = "type") val type: Refusal.Type,

    /* The refusal explanationfrom the model.  */
    @Json(name = "refusal") val refusal: kotlin.String,
) {

    /**
     * The type of the refusal. Always `refusal`.
     *
     * Values: refusal
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "refusal") refusal("refusal")
    }
}
