/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json

/**
 * Configuration options for a text response from the model. Can be plain text
 * or structured JSON data. Learn more: - [Text inputs and
 * outputs](/docs/guides/text) - [Structured Outputs](/docs/guides/structured-outputs)
 *
 * @param format
 */
data class ResponsePropertiesText(
    @Json(name = "format") val format: TextResponseFormatConfiguration? = null
) {}
