/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @param previousResponseId The unique ID of the previous response to the
 *   model. Use this to create multi-turn conversations. Learn more about
 *   [conversation state](/docs/guides/conversation-state).
 * @param model
 * @param reasoning
 * @param maxOutputTokens An upper bound for the number of tokens that can be
 *   generated for a response, including visible output tokens and
 *   [reasoning tokens](/docs/guides/reasoning).
 * @param instructions Inserts a system (or developer) message as the first item
 *   in the model's context. When using along with `previous_response_id`, the
 *   instructions from a previous response will be not be carried over to the
 *   next response. This makes it simple to swap out system (or developer)
 *   messages in new responses.
 * @param text
 * @param tools An array of tools the model may call while generating a
 *   response. You can specify which tool to use by setting the `tool_choice`
 *   parameter. The two categories of tools you can provide the model are: -
 *   **Built-in tools**: Tools that are provided by OpenAI that extend the
 *   model's capabilities, like [web search](/docs/guides/tools-web-search) or
 *   [file search](/docs/guides/tools-file-search). Learn more about [built-in
 *   tools](/docs/guides/tools). - **Function calls (custom tools)**: Functions
 *   that are defined by you, enabling the model to call your own code. Learn
 *   more about [function calling](/docs/guides/function-calling).
 * @param toolChoice
 * @param truncation The truncation strategy to use for the model response. -
 *   `auto`: If the context of this response and previous ones exceeds the
 *   model's context window size, the model will truncate the response to fit
 *   the context window by dropping input items in the middle of the
 *   conversation. - `disabled` (default): If a model response will exceed the
 *   context window size for a model, the request will fail with a 400 error.
 */
data class ResponseProperties(

    /* The unique ID of the previous response to the model. Use this to create multi-turn conversations. Learn more about  [conversation state](/docs/guides/conversation-state).  */
    @Json(name = "previous_response_id")
    val previousResponseId: kotlin.String? = null,
    @Json(name = "model") val model: ModelIdsResponses? = null,
    @Json(name = "reasoning") val reasoning: Reasoning? = null,

    /* An upper bound for the number of tokens that can be generated for a response, including visible output tokens and [reasoning tokens](/docs/guides/reasoning).  */
    @Json(name = "max_output_tokens") val maxOutputTokens: kotlin.Int? = null,

    /* Inserts a system (or developer) message as the first item in the model's context.  When using along with `previous_response_id`, the instructions from a previous response will be not be carried over to the next response. This makes it simple to swap out system (or developer) messages in new responses.  */
    @Json(name = "instructions") val instructions: kotlin.String? = null,
    @Json(name = "text") val text: ResponsePropertiesText? = null,

    /* An array of tools the model may call while generating a response. You  can specify which tool to use by setting the `tool_choice` parameter.  The two categories of tools you can provide the model are:  - **Built-in tools**: Tools that are provided by OpenAI that extend the   model's capabilities, like [web search](/docs/guides/tools-web-search)   or [file search](/docs/guides/tools-file-search). Learn more about   [built-in tools](/docs/guides/tools). - **Function calls (custom tools)**: Functions that are defined by you,   enabling the model to call your own code. Learn more about   [function calling](/docs/guides/function-calling).  */
    @Json(name = "tools") val tools: kotlin.collections.List<Tool>? = null,
    @Json(name = "tool_choice")
    val toolChoice: ResponsePropertiesToolChoice? = null,

    /* The truncation strategy to use for the model response. - `auto`: If the context of this response and previous ones exceeds   the model's context window size, the model will truncate the    response to fit the context window by dropping input items in the   middle of the conversation.  - `disabled` (default): If a model response will exceed the context window    size for a model, the request will fail with a 400 error.  */
    @Json(name = "truncation")
    val truncation: ResponseProperties.Truncation? = Truncation.disabled,
) {

    /**
     * The truncation strategy to use for the model response. - `auto`: If the
     * context of this response and previous ones exceeds the model's context
     * window size, the model will truncate the response to fit the context
     * window by dropping input items in the middle of the conversation. -
     * `disabled` (default): If a model response will exceed the context window
     * size for a model, the request will fail with a 400 error.
     *
     * Values: auto,disabled
     */
    @JsonClass(generateAdapter = false)
    enum class Truncation(val value: kotlin.String) {
        @Json(name = "auto") auto("auto"),
        @Json(name = "disabled") disabled("disabled"),
    }
}
