/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Emitted when a file search call is completed (results found).
 *
 * @param type The type of the event. Always
 *   `response.file_search_call.completed`.
 * @param outputIndex The index of the output item that the file search call is
 *   initiated.
 * @param itemId The ID of the output item that the file search call is
 *   initiated.
 */
data class ResponseFileSearchCallCompletedEvent(

    /* The type of the event. Always `response.file_search_call.completed`.  */
    @Json(name = "type") val type: ResponseFileSearchCallCompletedEvent.Type,

    /* The index of the output item that the file search call is initiated.  */
    @Json(name = "output_index") val outputIndex: kotlin.Int,

    /* The ID of the output item that the file search call is initiated.  */
    @Json(name = "item_id") val itemId: kotlin.String,
) {

    /**
     * The type of the event. Always `response.file_search_call.completed`.
     *
     * Values: responsePeriodFile_search_callPeriodCompleted
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "response.file_search_call.completed")
        responsePeriodFile_search_callPeriodCompleted(
            "response.file_search_call.completed"
        )
    }
}
