/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Emitted when there is a partial refusal text.
 *
 * @param type The type of the event. Always `response.refusal.delta`.
 * @param itemId The ID of the output item that the refusal text is added to.
 * @param outputIndex The index of the output item that the refusal text is
 *   added to.
 * @param contentIndex The index of the content part that the refusal text is
 *   added to.
 * @param delta The refusal text that is added.
 */
data class ResponseRefusalDeltaEvent(

    /* The type of the event. Always `response.refusal.delta`.  */
    @Json(name = "type") val type: ResponseRefusalDeltaEvent.Type,

    /* The ID of the output item that the refusal text is added to.  */
    @Json(name = "item_id") val itemId: kotlin.String,

    /* The index of the output item that the refusal text is added to.  */
    @Json(name = "output_index") val outputIndex: kotlin.Int,

    /* The index of the content part that the refusal text is added to.  */
    @Json(name = "content_index") val contentIndex: kotlin.Int,

    /* The refusal text that is added.  */
    @Json(name = "delta") val delta: kotlin.String,
) {

    /**
     * The type of the event. Always `response.refusal.delta`.
     *
     * Values: responsePeriodRefusalPeriodDelta
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "response.refusal.delta")
        responsePeriodRefusalPeriodDelta("response.refusal.delta")
    }
}
