/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The error code for the response.
 *
 * Values:
 * server_error,rate_limit_exceeded,invalid_prompt,vector_store_timeout,invalid_image,invalid_image_format,invalid_base64_image,invalid_image_url,image_too_large,image_too_small,image_parse_error,image_content_policy_violation,invalid_image_mode,image_file_too_large,unsupported_image_media_type,empty_image_file,failed_to_download_image,image_file_not_found
 */
@JsonClass(generateAdapter = false)
enum class ResponseErrorCode(val value: kotlin.String) {

    @Json(name = "server_error") server_error("server_error"),
    @Json(name = "rate_limit_exceeded")
    rate_limit_exceeded("rate_limit_exceeded"),
    @Json(name = "invalid_prompt") invalid_prompt("invalid_prompt"),
    @Json(name = "vector_store_timeout")
    vector_store_timeout("vector_store_timeout"),
    @Json(name = "invalid_image") invalid_image("invalid_image"),
    @Json(name = "invalid_image_format")
    invalid_image_format("invalid_image_format"),
    @Json(name = "invalid_base64_image")
    invalid_base64_image("invalid_base64_image"),
    @Json(name = "invalid_image_url") invalid_image_url("invalid_image_url"),
    @Json(name = "image_too_large") image_too_large("image_too_large"),
    @Json(name = "image_too_small") image_too_small("image_too_small"),
    @Json(name = "image_parse_error") image_parse_error("image_parse_error"),
    @Json(name = "image_content_policy_violation")
    image_content_policy_violation("image_content_policy_violation"),
    @Json(name = "invalid_image_mode") invalid_image_mode("invalid_image_mode"),
    @Json(name = "image_file_too_large")
    image_file_too_large("image_file_too_large"),
    @Json(name = "unsupported_image_media_type")
    unsupported_image_media_type("unsupported_image_media_type"),
    @Json(name = "empty_image_file") empty_image_file("empty_image_file"),
    @Json(name = "failed_to_download_image")
    failed_to_download_image("failed_to_download_image"),
    @Json(name = "image_file_not_found")
    image_file_not_found("image_file_not_found");

    /**
     * Override [toString()] to avoid using the enum variable name as the value,
     * and instead use the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different,
     * and ensures that the client sends the correct enum values to the server
     * always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null
         * otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? =
            if (data is ResponseErrorCode) "$data" else null

        /** Returns a valid [ResponseErrorCode] for [data], null otherwise. */
        fun decode(data: kotlin.Any?): ResponseErrorCode? =
            data?.let {
                val normalizedData = "$it".lowercase()
                values().firstOrNull { value ->
                    it == value || normalizedData == "$value".lowercase()
                }
            }
    }
}
