/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * An event that is emitted when a response finishes as incomplete.
 *
 * @param type The type of the event. Always `response.incomplete`.
 * @param response
 */
data class ResponseIncompleteEvent(

    /* The type of the event. Always `response.incomplete`.  */
    @Json(name = "type") val type: ResponseIncompleteEvent.Type,
    @Json(name = "response") val response: Response,
) {

    /**
     * The type of the event. Always `response.incomplete`.
     *
     * Values: responsePeriodIncomplete
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "response.incomplete")
        responsePeriodIncomplete("response.incomplete")
    }
}
