/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Emitted when a web search call is initiated.
 *
 * @param type The type of the event. Always
 *   `response.web_search_call.in_progress`.
 * @param outputIndex The index of the output item that the web search call is
 *   associated with.
 * @param itemId Unique ID for the output item associated with the web search
 *   call.
 */
data class ResponseWebSearchCallInProgressEvent(

    /* The type of the event. Always `response.web_search_call.in_progress`.  */
    @Json(name = "type") val type: ResponseWebSearchCallInProgressEvent.Type,

    /* The index of the output item that the web search call is associated with.  */
    @Json(name = "output_index") val outputIndex: kotlin.Int,

    /* Unique ID for the output item associated with the web search call.  */
    @Json(name = "item_id") val itemId: kotlin.String,
) {

    /**
     * The type of the event. Always `response.web_search_call.in_progress`.
     *
     * Values: responsePeriodWeb_search_callPeriodIn_progress
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "response.web_search_call.in_progress")
        responsePeriodWeb_search_callPeriodIn_progress(
            "response.web_search_call.in_progress"
        )
    }
}
