/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A list of Response items.
 *
 * @param `object` The type of object returned, must be `list`.
 * @param `data` A list of items used to generate this response.
 * @param hasMore Whether there are more items available.
 * @param firstId The ID of the first item in the list.
 * @param lastId The ID of the last item in the list.
 */
data class ResponseItemList(

    /* The type of object returned, must be `list`. */
    @Json(name = "object") val `object`: ResponseItemList.`Object`,

    /* A list of items used to generate this response. */
    @Json(name = "data") val `data`: kotlin.collections.List<ItemResource>,

    /* Whether there are more items available. */
    @Json(name = "has_more") val hasMore: kotlin.Boolean,

    /* The ID of the first item in the list. */
    @Json(name = "first_id") val firstId: kotlin.String,

    /* The ID of the last item in the list. */
    @Json(name = "last_id") val lastId: kotlin.String,
) {

    /**
     * The type of object returned, must be `list`.
     *
     * Values: list
     */
    @JsonClass(generateAdapter = false)
    enum class `Object`(val value: kotlin.String) {
        @Json(name = "list") list("list")
    }
}
