/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Emitted when a code interpreter call is in progress.
 *
 * @param type The type of the event. Always
 *   `response.code_interpreter_call.in_progress`.
 * @param outputIndex The index of the output item that the code interpreter
 *   call is in progress.
 * @param codeInterpreterCall
 */
data class ResponseCodeInterpreterCallInProgressEvent(

    /* The type of the event. Always `response.code_interpreter_call.in_progress`.  */
    @Json(name = "type")
    val type: ResponseCodeInterpreterCallInProgressEvent.Type,

    /* The index of the output item that the code interpreter call is in progress.  */
    @Json(name = "output_index") val outputIndex: kotlin.Int,
    @Json(name = "code_interpreter_call")
    val codeInterpreterCall: CodeInterpreterToolCall,
) {

    /**
     * The type of the event. Always
     * `response.code_interpreter_call.in_progress`.
     *
     * Values: responsePeriodCode_interpreter_callPeriodIn_progress
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "response.code_interpreter_call.in_progress")
        responsePeriodCode_interpreter_callPeriodIn_progress(
            "response.code_interpreter_call.in_progress"
        )
    }
}
