/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Emitted when a text annotation is added.
 *
 * @param type The type of the event. Always
 *   `response.output_text.annotation.added`.
 * @param itemId The ID of the output item that the text annotation was added
 *   to.
 * @param outputIndex The index of the output item that the text annotation was
 *   added to.
 * @param contentIndex The index of the content part that the text annotation
 *   was added to.
 * @param annotationIndex The index of the annotation that was added.
 * @param `annotation`
 */
data class ResponseTextAnnotationDeltaEvent(

    /* The type of the event. Always `response.output_text.annotation.added`.  */
    @Json(name = "type") val type: ResponseTextAnnotationDeltaEvent.Type,

    /* The ID of the output item that the text annotation was added to.  */
    @Json(name = "item_id") val itemId: kotlin.String,

    /* The index of the output item that the text annotation was added to.  */
    @Json(name = "output_index") val outputIndex: kotlin.Int,

    /* The index of the content part that the text annotation was added to.  */
    @Json(name = "content_index") val contentIndex: kotlin.Int,

    /* The index of the annotation that was added.  */
    @Json(name = "annotation_index") val annotationIndex: kotlin.Int,
    @Json(name = "annotation") val `annotation`: Annotation,
) {

    /**
     * The type of the event. Always `response.output_text.annotation.added`.
     *
     * Values: responsePeriodOutput_textPeriodAnnotationPeriodAdded
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "response.output_text.annotation.added")
        responsePeriodOutput_textPeriodAnnotationPeriodAdded(
            "response.output_text.annotation.added"
        )
    }
}
