/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * An event that is emitted when a response fails.
 *
 * @param type The type of the event. Always `response.failed`.
 * @param response
 */
data class ResponseFailedEvent(

    /* The type of the event. Always `response.failed`.  */
    @Json(name = "type") val type: ResponseFailedEvent.Type,
    @Json(name = "response") val response: Response,
) {

    /**
     * The type of the event. Always `response.failed`.
     *
     * Values: responsePeriodFailed
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "response.failed") responsePeriodFailed("response.failed")
    }
}
