/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Emitted when the audio response is complete.
 *
 * @param type The type of the event. Always `response.audio.done`.
 */
data class ResponseAudioDoneEvent(

    /* The type of the event. Always `response.audio.done`.  */
    @Json(name = "type") val type: ResponseAudioDoneEvent.Type
) {

    /**
     * The type of the event. Always `response.audio.done`.
     *
     * Values: responsePeriodAudioPeriodDone
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "response.audio.done")
        responsePeriodAudioPeriodDone("response.audio.done")
    }
}
