/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Emitted when a partial code snippet is added by the code interpreter.
 *
 * @param type The type of the event. Always
 *   `response.code_interpreter_call.code.delta`.
 * @param outputIndex The index of the output item that the code interpreter
 *   call is in progress.
 * @param delta The partial code snippet added by the code interpreter.
 */
data class ResponseCodeInterpreterCallCodeDeltaEvent(

    /* The type of the event. Always `response.code_interpreter_call.code.delta`.  */
    @Json(name = "type")
    val type: ResponseCodeInterpreterCallCodeDeltaEvent.Type,

    /* The index of the output item that the code interpreter call is in progress.  */
    @Json(name = "output_index") val outputIndex: kotlin.Int,

    /* The partial code snippet added by the code interpreter.  */
    @Json(name = "delta") val delta: kotlin.String,
) {

    /**
     * The type of the event. Always
     * `response.code_interpreter_call.code.delta`.
     *
     * Values: responsePeriodCode_interpreter_callPeriodCodePeriodDelta
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "response.code_interpreter_call.code.delta")
        responsePeriodCode_interpreter_callPeriodCodePeriodDelta(
            "response.code_interpreter_call.code.delta"
        )
    }
}
