/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Emitted when code snippet output is finalized by the code interpreter.
 *
 * @param type The type of the event. Always
 *   `response.code_interpreter_call.code.done`.
 * @param outputIndex The index of the output item that the code interpreter
 *   call is in progress.
 * @param code The final code snippet output by the code interpreter.
 */
data class ResponseCodeInterpreterCallCodeDoneEvent(

    /* The type of the event. Always `response.code_interpreter_call.code.done`.  */
    @Json(name = "type")
    val type: ResponseCodeInterpreterCallCodeDoneEvent.Type,

    /* The index of the output item that the code interpreter call is in progress.  */
    @Json(name = "output_index") val outputIndex: kotlin.Int,

    /* The final code snippet output by the code interpreter.  */
    @Json(name = "code") val code: kotlin.String,
) {

    /**
     * The type of the event. Always `response.code_interpreter_call.code.done`.
     *
     * Values: responsePeriodCode_interpreter_callPeriodCodePeriodDone
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "response.code_interpreter_call.code.done")
        responsePeriodCode_interpreter_callPeriodCodePeriodDone(
            "response.code_interpreter_call.code.done"
        )
    }
}
