/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Emitted when the full audio transcript is completed.
 *
 * @param type The type of the event. Always `response.audio.transcript.done`.
 */
data class ResponseAudioTranscriptDoneEvent(

    /* The type of the event. Always `response.audio.transcript.done`.  */
    @Json(name = "type") val type: ResponseAudioTranscriptDoneEvent.Type
) {

    /**
     * The type of the event. Always `response.audio.transcript.done`.
     *
     * Values: responsePeriodAudioPeriodTranscriptPeriodDone
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "response.audio.transcript.done")
        responsePeriodAudioPeriodTranscriptPeriodDone(
            "response.audio.transcript.done"
        )
    }
}
