/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models

import com.squareup.moshi.Json

/**
 * For now, this is always going to be an empty object.
 *
 * @param rankingOptions 
 * @param results The results of the file search.
 */


data class RunStepDetailsToolCallsFileSearchObjectFileSearch (

    @Json(name = "ranking_options")
    val rankingOptions: RunStepDetailsToolCallsFileSearchRankingOptionsObject? = null,

    /* The results of the file search. */
    @Json(name = "results")
    val results: kotlin.collections.List<RunStepDetailsToolCallsFileSearchResultObject>? = null

) {


}

