/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models

import com.openai.models.RunStepObject
import com.openai.models.RunStepStreamEventOneOf
import com.openai.models.RunStepStreamEventOneOf1
import com.openai.models.RunStepStreamEventOneOf2
import com.openai.models.RunStepStreamEventOneOf3
import com.openai.models.RunStepStreamEventOneOf4
import com.openai.models.RunStepStreamEventOneOf5
import com.openai.models.RunStepStreamEventOneOf6

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param event 
 * @param `data` 
 */


data class RunStepStreamEvent (

    @Json(name = "event")
    val event: RunStepStreamEvent.Event,

    @Json(name = "data")
    val `data`: RunStepObject

) {

    /**
     * 
     *
     * Values: threadPeriodRunPeriodStepPeriodExpired
     */
    @JsonClass(generateAdapter = false)
    enum class Event(val value: kotlin.String) {
        @Json(name = "thread.run.step.expired") threadPeriodRunPeriodStepPeriodExpired("thread.run.step.expired");
    }

}

