/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * An object specifying the format that the model must output. Configuring `{
 * \"type\": \"json_schema\" }` enables Structured Outputs, which ensures the
 * model will match your supplied JSON schema. Learn more in the
 * [Structured Outputs guide](/docs/guides/structured-outputs). The default
 * format is `{ \"type\": \"text\" }` with no additional options. **Not
 * recommended for gpt-4o and newer models:** Setting to `{ \"type\":
 * \"json_object\" }` enables the older JSON mode, which ensures the message the
 * model generates is valid JSON. Using `json_schema` is preferred for models
 * that support it.
 *
 * @param type The type of response format being defined. Always `text`.
 * @param schema The schema for the response format, described as a JSON Schema
 *   object. Learn how to build JSON schemas [here](https://json-schema.org/).
 * @param description A description of what the response format is for, used by
 *   the model to determine how to respond in the format.
 * @param name The name of the response format. Must be a-z, A-Z, 0-9, or
 *   contain underscores and dashes, with a maximum length of 64.
 * @param strict Whether to enable strict schema adherence when generating the
 *   output. If set to true, the model will always follow the exact schema
 *   defined in the `schema` field. Only a subset of JSON Schema is supported
 *   when `strict` is `true`. To learn more, read the
 *   [Structured Outputs guide](/docs/guides/structured-outputs).
 */
data class TextResponseFormatConfiguration(

    /* The type of response format being defined. Always `text`. */
    @Json(name = "type") val type: TextResponseFormatConfiguration.Type,

    /* The schema for the response format, described as a JSON Schema object. Learn how to build JSON schemas [here](https://json-schema.org/).  */
    @Json(name = "schema")
    val schema: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    /* A description of what the response format is for, used by the model to determine how to respond in the format.  */
    @Json(name = "description") val description: kotlin.String? = null,

    /* The name of the response format. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.  */
    @Json(name = "name") val name: kotlin.String? = null,

    /* Whether to enable strict schema adherence when generating the output. If set to true, the model will always follow the exact schema defined in the `schema` field. Only a subset of JSON Schema is supported when `strict` is `true`. To learn more, read the [Structured Outputs guide](/docs/guides/structured-outputs).  */
    @Json(name = "strict") val strict: kotlin.Boolean? = false,
) {

    /**
     * The type of response format being defined. Always `text`.
     *
     * Values: text,json_schema,json_object
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "text") text("text"),
        @Json(name = "json_schema") json_schema("json_schema"),
        @Json(name = "json_object") json_object("json_object"),
    }
}
