/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Use this option to force the model to call a specific function.
 *
 * @param type For function calling, the type is always `function`.
 * @param name The name of the function to call.
 */
data class ToolChoiceFunction(

    /* For function calling, the type is always `function`. */
    @Json(name = "type") val type: ToolChoiceFunction.Type,

    /* The name of the function to call. */
    @Json(name = "name") val name: kotlin.String,
) {

    /**
     * For function calling, the type is always `function`.
     *
     * Values: function
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "function") function("function")
    }
}
