/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Controls which (if any) tool is called by the model. `none` means the model
 * will not call any tool and instead generates a message. `auto` means the
 * model can pick between generating a message or calling one or more tools.
 * `required` means the model must call one or more tools.
 *
 * Values: none,auto,required
 */
@JsonClass(generateAdapter = false)
enum class ToolChoiceOptions(val value: kotlin.String) {

    @Json(name = "none") none("none"),
    @Json(name = "auto") auto("auto"),
    @Json(name = "required") required("required");

    /**
     * Override [toString()] to avoid using the enum variable name as the value,
     * and instead use the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different,
     * and ensures that the client sends the correct enum values to the server
     * always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null
         * otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? =
            if (data is ToolChoiceOptions) "$data" else null

        /** Returns a valid [ToolChoiceOptions] for [data], null otherwise. */
        fun decode(data: kotlin.Any?): ToolChoiceOptions? =
            data?.let {
                val normalizedData = "$it".lowercase()
                values().firstOrNull { value ->
                    it == value || normalizedData == "$value".lowercase()
                }
            }
    }
}
