/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Emitted when there is an additional text delta. This is also the first event
 * emitted when the transcription starts. Only emitted when you
 * [create a transcription](/docs/api-reference/audio/create-transcription) with
 * the `Stream` parameter set to `true`.
 *
 * @param type The type of the event. Always `transcript.text.delta`.
 * @param delta The text delta that was additionally transcribed.
 * @param logprobs The log probabilities of the delta. Only included if you
 *   [create a transcription](/docs/api-reference/audio/create-transcription)
 *   with the `include[]` parameter set to `logprobs`.
 */
data class TranscriptTextDeltaEvent(

    /* The type of the event. Always `transcript.text.delta`.  */
    @Json(name = "type") val type: TranscriptTextDeltaEvent.Type,

    /* The text delta that was additionally transcribed.  */
    @Json(name = "delta") val delta: kotlin.String,

    /* The log probabilities of the delta. Only included if you [create a transcription](/docs/api-reference/audio/create-transcription) with the `include[]` parameter set to `logprobs`.  */
    @Json(name = "logprobs")
    val logprobs: kotlin.collections.List<LogProbProperties>? = null,
) {

    /**
     * The type of the event. Always `transcript.text.delta`.
     *
     * Values: transcriptPeriodTextPeriodDelta
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "transcript.text.delta")
        transcriptPeriodTextPeriodDelta("transcript.text.delta")
    }
}
