/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @param anchor Anchor timestamp after which the expiration policy applies.
 *   Supported anchors: `last_active_at`.
 * @param days The number of days after the anchor time that the vector store
 *   will expire.
 */
data class UpdateVectorStoreRequestExpiresAfter(

    /* Anchor timestamp after which the expiration policy applies. Supported anchors: `last_active_at`. */
    @Json(name = "anchor")
    val anchor: UpdateVectorStoreRequestExpiresAfter.Anchor,

    /* The number of days after the anchor time that the vector store will expire. */
    @Json(name = "days") val days: kotlin.Int,
) {

    /**
     * Anchor timestamp after which the expiration policy applies. Supported
     * anchors: `last_active_at`.
     *
     * Values: last_active_at
     */
    @JsonClass(generateAdapter = false)
    enum class Anchor(val value: kotlin.String) {
        @Json(name = "last_active_at") last_active_at("last_active_at")
    }
}
