/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @param type The type of content.
 * @param text The text content returned from search.
 */
data class VectorStoreSearchResultContentObject(

    /* The type of content. */
    @Json(name = "type") val type: VectorStoreSearchResultContentObject.Type,

    /* The text content returned from search. */
    @Json(name = "text") val text: kotlin.String,
) {

    /**
     * The type of content.
     *
     * Values: text
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "text") text("text")
    }
}
