/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json

/**
 * @param fileId The ID of the vector store file.
 * @param filename The name of the vector store file.
 * @param score The similarity score for the result.
 * @param attributes Set of 16 key-value pairs that can be attached to an
 *   object. This can be useful for storing additional information about the
 *   object in a structured format, and querying for objects via API or the
 *   dashboard. Keys are strings with a maximum length of 64 characters. Values
 *   are strings with a maximum length of 512 characters, booleans, or numbers.
 * @param content Content chunks from the file.
 */
data class VectorStoreSearchResultItem(

    /* The ID of the vector store file. */
    @Json(name = "file_id") val fileId: kotlin.String,

    /* The name of the vector store file. */
    @Json(name = "filename") val filename: kotlin.String,

    /* The similarity score for the result. */
    @Json(name = "score") val score: java.math.BigDecimal,

    /* Set of 16 key-value pairs that can be attached to an object. This can be  useful for storing additional information about the object in a structured  format, and querying for objects via API or the dashboard. Keys are strings  with a maximum length of 64 characters. Values are strings with a maximum  length of 512 characters, booleans, or numbers.  */
    @Json(name = "attributes")
    val attributes:
        kotlin.collections.Map<kotlin.String, VectorStoreFileAttributesValue>?,

    /* Content chunks from the file. */
    @Json(name = "content")
    val content: kotlin.collections.List<VectorStoreSearchResultContentObject>,
) {}
