/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json

/**
 * @param query
 * @param rewriteQuery Whether to rewrite the natural language query for vector
 *   search.
 * @param maxNumResults The maximum number of results to return. This number
 *   should be between 1 and 50 inclusive.
 * @param filters
 * @param rankingOptions
 */
data class VectorStoreSearchRequest(
    @Json(name = "query") val query: VectorStoreSearchRequestQuery,

    /* Whether to rewrite the natural language query for vector search. */
    @Json(name = "rewrite_query") val rewriteQuery: kotlin.Boolean? = false,

    /* The maximum number of results to return. This number should be between 1 and 50 inclusive. */
    @Json(name = "max_num_results") val maxNumResults: kotlin.Int? = 10,
    @Json(name = "filters") val filters: FileSearchToolFilters? = null,
    @Json(name = "ranking_options")
    val rankingOptions: VectorStoreSearchRequestRankingOptions? = null,
) {}
