/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json

// openai-openapi-kotlin changes begin
/**
 * The voice the model uses to respond. Voice cannot be changed during the
 * session once the model has responded with audio at least once. Current voice
 * options are `alloy`, `ash`, `ballad`, `coral`, `echo` `sage`, `shimmer` and
 * `verse`.
 *
 * Values: alloy,ash,ballad,coral,echo,sage,shimmer,verse
 */
enum class VoiceIdsShared(val value: kotlin.String) {
    @Json(name = "alloy") alloy("alloy"),
    @Json(name = "ash") ash("ash"),
    @Json(name = "ballad") ballad("ballad"),
    @Json(name = "coral") coral("coral"),
    @Json(name = "echo") echo("echo"),
    @Json(name = "sage") sage("sage"),
    @Json(name = "shimmer") shimmer("shimmer"),
    @Json(name = "verse") verse("verse"),
}
// openai-openapi-kotlin changes end
