/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json

/**
 * This tool searches the web for relevant results to use in a response. Learn
 * more about the
 * [web search tool](/docs/guides/tools-web-search?api-mode=chat).
 *
 * @param userLocation
 * @param searchContextSize
 */
data class WebSearch(
    @Json(name = "user_location")
    val userLocation: WebSearchUserLocation? = null,
    @Json(name = "search_context_size")
    val searchContextSize: WebSearchContextSize? = WebSearchContextSize.medium,
) {}
