/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @param type The type of location approximation. Always `approximate`.
 * @param country The two-letter
 *   [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1) of the user,
 *   e.g. `US`.
 * @param region Free text input for the region of the user, e.g. `California`.
 * @param city Free text input for the city of the user, e.g. `San Francisco`.
 * @param timezone The
 *   [IANA timezone](https://timeapi.io/documentation/iana-timezones) of the
 *   user, e.g. `America/Los_Angeles`.
 */
data class WebSearchToolUserLocation(

    /* The type of location approximation. Always `approximate`.  */
    @Json(name = "type") val type: WebSearchToolUserLocation.Type,

    /* The two-letter  [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1) of the user, e.g. `US`.  */
    @Json(name = "country") val country: kotlin.String? = null,

    /* Free text input for the region of the user, e.g. `California`.  */
    @Json(name = "region") val region: kotlin.String? = null,

    /* Free text input for the city of the user, e.g. `San Francisco`.  */
    @Json(name = "city") val city: kotlin.String? = null,

    /* The [IANA timezone](https://timeapi.io/documentation/iana-timezones)  of the user, e.g. `America/Los_Angeles`.  */
    @Json(name = "timezone") val timezone: kotlin.String? = null,
) {

    /**
     * The type of location approximation. Always `approximate`.
     *
     * Values: approximate
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "approximate") approximate("approximate")
    }
}
