/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class AnnotationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Annotation
        // val modelInstance = Annotation()

        // to test the property `type` - The type of the file citation. Always
        // `file_citation`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `index` - The index of the file in the list of
        // files.
        should("test index") {
            // uncomment below to test the property
            // modelInstance.index shouldBe ("TODO")
        }

        // to test the property `fileId` - The ID of the file.
        should("test fileId") {
            // uncomment below to test the property
            // modelInstance.fileId shouldBe ("TODO")
        }

        // to test the property `url` - The URL of the web resource.
        should("test url") {
            // uncomment below to test the property
            // modelInstance.url shouldBe ("TODO")
        }

        // to test the property `title` - The title of the web resource.
        should("test title") {
            // uncomment below to test the property
            // modelInstance.title shouldBe ("TODO")
        }

        // to test the property `startIndex` - The index of the first character
        // of the URL citation in the message.
        should("test startIndex") {
            // uncomment below to test the property
            // modelInstance.startIndex shouldBe ("TODO")
        }

        // to test the property `endIndex` - The index of the last character of
        // the URL citation in the message.
        should("test endIndex") {
            // uncomment below to test the property
            // modelInstance.endIndex shouldBe ("TODO")
        }
    }
}
