/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openai.models.ArrayOfContentPartsInner
import com.openai.models.MessageContentImageFileObject
import com.openai.models.MessageContentImageFileObjectImageFile
import com.openai.models.MessageContentImageUrlObject
import com.openai.models.MessageContentImageUrlObjectImageUrl
import com.openai.models.MessageRequestContentTextObject

class ArrayOfContentPartsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ArrayOfContentPartsInner
        //val modelInstance = ArrayOfContentPartsInner()

        // to test the property `type` - Always `image_file`.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `imageFile`
        should("test imageFile") {
            // uncomment below to test the property
            //modelInstance.imageFile shouldBe ("TODO")
        }

        // to test the property `imageUrl`
        should("test imageUrl") {
            // uncomment below to test the property
            //modelInstance.imageUrl shouldBe ("TODO")
        }

        // to test the property `text` - Text content to be sent to the model
        should("test text") {
            // uncomment below to test the property
            //modelInstance.text shouldBe ("TODO")
        }

    }
}
