/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class AssistantToolsFileSearchTypeOnlyTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // AssistantToolsFileSearchTypeOnly
        // val modelInstance = AssistantToolsFileSearchTypeOnly()

        // to test the property `type` - The type of tool being defined:
        // `file_search`
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }
    }
}
