/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openai.models.AssistantObjectToolsInner
import com.openai.models.AssistantToolsCode
import com.openai.models.AssistantToolsFileSearch
import com.openai.models.AssistantToolsFileSearchFileSearch
import com.openai.models.AssistantToolsFunction
import com.openai.models.FunctionObject

class AssistantObjectToolsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AssistantObjectToolsInner
        //val modelInstance = AssistantObjectToolsInner()

        // to test the property `type` - The type of tool being defined: `code_interpreter`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `function`
        should("test function") {
            // uncomment below to test the property
            //modelInstance.function shouldBe ("TODO")
        }

        // to test the property `fileSearch`
        should("test fileSearch") {
            // uncomment below to test the property
            //modelInstance.fileSearch shouldBe ("TODO")
        }

    }
}
