/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class AuditLogProjectCreatedTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuditLogProjectCreated
        // val modelInstance = AuditLogProjectCreated()

        // to test the property `id` - The project ID.
        should("test id") {
            // uncomment below to test the property
            // modelInstance.id shouldBe ("TODO")
        }

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            // modelInstance.`data` shouldBe ("TODO")
        }
    }
}
