/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class AuditLogServiceAccountUpdatedChangesRequestedTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // AuditLogServiceAccountUpdatedChangesRequested
        // val modelInstance = AuditLogServiceAccountUpdatedChangesRequested()

        // to test the property `role` - The role of the service account. Is
        // either `owner` or `member`.
        should("test role") {
            // uncomment below to test the property
            // modelInstance.role shouldBe ("TODO")
        }
    }
}
