/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ChatCompletionRequestMessageContentPartRefusalTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // ChatCompletionRequestMessageContentPartRefusal
        // val modelInstance = ChatCompletionRequestMessageContentPartRefusal()

        // to test the property `type` - The type of the content part.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `refusal` - The refusal message generated by the
        // model.
        should("test refusal") {
            // uncomment below to test the property
            // modelInstance.refusal shouldBe ("TODO")
        }
    }
}
