/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ChatCompletionMessageListDataInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // ChatCompletionMessageListDataInner
        // val modelInstance = ChatCompletionMessageListDataInner()

        // to test the property `content` - The contents of the message.
        should("test content") {
            // uncomment below to test the property
            // modelInstance.content shouldBe ("TODO")
        }

        // to test the property `refusal` - The refusal message generated by the
        // model.
        should("test refusal") {
            // uncomment below to test the property
            // modelInstance.refusal shouldBe ("TODO")
        }

        // to test the property `role` - The role of the author of this message.
        should("test role") {
            // uncomment below to test the property
            // modelInstance.role shouldBe ("TODO")
        }

        // to test the property `id` - The identifier of the chat message.
        should("test id") {
            // uncomment below to test the property
            // modelInstance.id shouldBe ("TODO")
        }

        // to test the property `toolCalls` - The tool calls generated by the
        // model, such as function calls.
        should("test toolCalls") {
            // uncomment below to test the property
            // modelInstance.toolCalls shouldBe ("TODO")
        }

        // to test the property `annotations` - Annotations for the message,
        // when applicable, as when using the [web search
        // tool](/docs/guides/tools-web-search?api-mode=chat).
        should("test annotations") {
            // uncomment below to test the property
            // modelInstance.annotations shouldBe ("TODO")
        }

        // to test the property `functionCall`
        should("test functionCall") {
            // uncomment below to test the property
            // modelInstance.functionCall shouldBe ("TODO")
        }

        // to test the property `audio`
        should("test audio") {
            // uncomment below to test the property
            // modelInstance.audio shouldBe ("TODO")
        }
    }
}
