/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ChatCompletionRequestMessageContentPartFileTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // ChatCompletionRequestMessageContentPartFile
        // val modelInstance = ChatCompletionRequestMessageContentPartFile()

        // to test the property `type` - The type of the content part. Always
        // `file`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `file`
        should("test file") {
            // uncomment below to test the property
            // modelInstance.file shouldBe ("TODO")
        }
    }
}
