/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ChatCompletionRequestMessageContentPartAudioInputAudioTest :
    ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // ChatCompletionRequestMessageContentPartAudioInputAudio
        // val modelInstance =
        // ChatCompletionRequestMessageContentPartAudioInputAudio()

        // to test the property ``data`` - Base64 encoded audio data.
        should("test `data`") {
            // uncomment below to test the property
            // modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `format` - The format of the encoded audio data.
        // Currently supports \"wav\" and \"mp3\".
        should("test format") {
            // uncomment below to test the property
            // modelInstance.format shouldBe ("TODO")
        }
    }
}
