/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openai.models.ChatCompletionRequestMessageContentPartAudio
import com.openai.models.ChatCompletionRequestMessageContentPartAudioInputAudio

class ChatCompletionRequestMessageContentPartAudioTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChatCompletionRequestMessageContentPartAudio
        //val modelInstance = ChatCompletionRequestMessageContentPartAudio()

        // to test the property `type` - The type of the content part. Always `input_audio`.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `inputAudio`
        should("test inputAudio") {
            // uncomment below to test the property
            //modelInstance.inputAudio shouldBe ("TODO")
        }

    }
}
