/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ClickTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Click
        // val modelInstance = Click()

        // to test the property `type` - Specifies the event type. For a click
        // action, this property is  always set to `click`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `button` - Indicates which mouse button was
        // pressed during the click. One of `left`, `right`, `wheel`, `back`, or
        // `forward`.
        should("test button") {
            // uncomment below to test the property
            // modelInstance.button shouldBe ("TODO")
        }

        // to test the property `x` - The x-coordinate where the click occurred.
        should("test x") {
            // uncomment below to test the property
            // modelInstance.x shouldBe ("TODO")
        }

        // to test the property `y` - The y-coordinate where the click occurred.
        should("test y") {
            // uncomment below to test the property
            // modelInstance.y shouldBe ("TODO")
        }
    }
}
