/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class CodeInterpreterFileOutputFilesInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // CodeInterpreterFileOutputFilesInner
        // val modelInstance = CodeInterpreterFileOutputFilesInner()

        // to test the property `mimeType` - The MIME type of the file.
        should("test mimeType") {
            // uncomment below to test the property
            // modelInstance.mimeType shouldBe ("TODO")
        }

        // to test the property `fileId` - The ID of the file.
        should("test fileId") {
            // uncomment below to test the property
            // modelInstance.fileId shouldBe ("TODO")
        }
    }
}
