/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class CodeInterpreterToolCallTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CodeInterpreterToolCall
        // val modelInstance = CodeInterpreterToolCall()

        // to test the property `id` - The unique ID of the code interpreter
        // tool call.
        should("test id") {
            // uncomment below to test the property
            // modelInstance.id shouldBe ("TODO")
        }

        // to test the property `type` - The type of the code interpreter tool
        // call. Always `code_interpreter_call`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `code` - The code to run.
        should("test code") {
            // uncomment below to test the property
            // modelInstance.code shouldBe ("TODO")
        }

        // to test the property `status` - The status of the code interpreter
        // tool call.
        should("test status") {
            // uncomment below to test the property
            // modelInstance.status shouldBe ("TODO")
        }

        // to test the property `results` - The results of the code interpreter
        // tool call.
        should("test results") {
            // uncomment below to test the property
            // modelInstance.results shouldBe ("TODO")
        }
    }
}
