/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ComputerToolCallSafetyCheckTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ComputerToolCallSafetyCheck
        // val modelInstance = ComputerToolCallSafetyCheck()

        // to test the property `id` - The ID of the pending safety check.
        should("test id") {
            // uncomment below to test the property
            // modelInstance.id shouldBe ("TODO")
        }

        // to test the property `code` - The type of the pending safety check.
        should("test code") {
            // uncomment below to test the property
            // modelInstance.code shouldBe ("TODO")
        }

        // to test the property `message` - Details about the pending safety
        // check.
        should("test message") {
            // uncomment below to test the property
            // modelInstance.message shouldBe ("TODO")
        }
    }
}
