/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class CompoundFilterTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CompoundFilter
        // val modelInstance = CompoundFilter()

        // to test the property `type` - Type of operation: `and` or `or`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `filters` - Array of filters to combine. Items
        // can be `ComparisonFilter` or `CompoundFilter`.
        should("test filters") {
            // uncomment below to test the property
            // modelInstance.filters shouldBe ("TODO")
        }
    }
}
