/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ComputerScreenshotImageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ComputerScreenshotImage
        // val modelInstance = ComputerScreenshotImage()

        // to test the property `type` - Specifies the event type. For a
        // computer screenshot, this property is  always set to
        // `computer_screenshot`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `imageUrl` - The URL of the screenshot image.
        should("test imageUrl") {
            // uncomment below to test the property
            // modelInstance.imageUrl shouldBe ("TODO")
        }

        // to test the property `fileId` - The identifier of an uploaded file
        // that contains the screenshot.
        should("test fileId") {
            // uncomment below to test the property
            // modelInstance.fileId shouldBe ("TODO")
        }
    }
}
