/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ComputerToolCallTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ComputerToolCall
        // val modelInstance = ComputerToolCall()

        // to test the property `type` - The type of the computer call. Always
        // `computer_call`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `id` - The unique ID of the computer call.
        should("test id") {
            // uncomment below to test the property
            // modelInstance.id shouldBe ("TODO")
        }

        // to test the property `callId` - An identifier used when responding to
        // the tool call with output.
        should("test callId") {
            // uncomment below to test the property
            // modelInstance.callId shouldBe ("TODO")
        }

        // to test the property `action`
        should("test action") {
            // uncomment below to test the property
            // modelInstance.action shouldBe ("TODO")
        }

        // to test the property `pendingSafetyChecks` - The pending safety
        // checks for the computer call.
        should("test pendingSafetyChecks") {
            // uncomment below to test the property
            // modelInstance.pendingSafetyChecks shouldBe ("TODO")
        }

        // to test the property `status` - The status of the item. One of
        // `in_progress`, `completed`, or `incomplete`. Populated when items are
        // returned via API.
        should("test status") {
            // uncomment below to test the property
            // modelInstance.status shouldBe ("TODO")
        }
    }
}
