/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ComputerToolCallOutputResourceTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // ComputerToolCallOutputResource
        // val modelInstance = ComputerToolCallOutputResource()

        // to test the property `type` - The type of the computer tool call
        // output. Always `computer_call_output`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `id` - The unique ID of the computer call tool
        // output.
        should("test id") {
            // uncomment below to test the property
            // modelInstance.id shouldBe ("TODO")
        }

        // to test the property `callId` - The ID of the computer tool call that
        // produced the output.
        should("test callId") {
            // uncomment below to test the property
            // modelInstance.callId shouldBe ("TODO")
        }

        // to test the property `output`
        should("test output") {
            // uncomment below to test the property
            // modelInstance.output shouldBe ("TODO")
        }

        // to test the property `acknowledgedSafetyChecks` - The safety checks
        // reported by the API that have been acknowledged by the  developer.
        should("test acknowledgedSafetyChecks") {
            // uncomment below to test the property
            // modelInstance.acknowledgedSafetyChecks shouldBe ("TODO")
        }

        // to test the property `status` - The status of the message input. One
        // of `in_progress`, `completed`, or `incomplete`. Populated when input
        // items are returned via API.
        should("test status") {
            // uncomment below to test the property
            // modelInstance.status shouldBe ("TODO")
        }
    }
}
