/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ComputerActionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ComputerAction
        // val modelInstance = ComputerAction()

        // to test the property `type` - Specifies the event type. For a click
        // action, this property is  always set to `click`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `button` - Indicates which mouse button was
        // pressed during the click. One of `left`, `right`, `wheel`, `back`, or
        // `forward`.
        should("test button") {
            // uncomment below to test the property
            // modelInstance.button shouldBe ("TODO")
        }

        // to test the property `x` - The x-coordinate where the scroll
        // occurred.
        should("test x") {
            // uncomment below to test the property
            // modelInstance.x shouldBe ("TODO")
        }

        // to test the property `y` - The y-coordinate where the scroll
        // occurred.
        should("test y") {
            // uncomment below to test the property
            // modelInstance.y shouldBe ("TODO")
        }

        // to test the property `path` - An array of coordinates representing
        // the path of the drag action. Coordinates will appear as an array of
        // objects, eg ``` [   { x: 100, y: 200 },   { x: 200, y: 300 } ] ```
        should("test path") {
            // uncomment below to test the property
            // modelInstance.path shouldBe ("TODO")
        }

        // to test the property `propertyKeys` - The combination of keys the
        // model is requesting to be pressed. This is an array of strings, each
        // representing a key.
        should("test propertyKeys") {
            // uncomment below to test the property
            // modelInstance.propertyKeys shouldBe ("TODO")
        }

        // to test the property `scrollX` - The horizontal scroll distance.
        should("test scrollX") {
            // uncomment below to test the property
            // modelInstance.scrollX shouldBe ("TODO")
        }

        // to test the property `scrollY` - The vertical scroll distance.
        should("test scrollY") {
            // uncomment below to test the property
            // modelInstance.scrollY shouldBe ("TODO")
        }

        // to test the property `text` - The text to type.
        should("test text") {
            // uncomment below to test the property
            // modelInstance.text shouldBe ("TODO")
        }
    }
}
