/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class CreateMessageRequestAttachmentsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // CreateMessageRequestAttachmentsInner
        // val modelInstance = CreateMessageRequestAttachmentsInner()

        // to test the property `fileId` - The ID of the file to attach to the
        // message.
        should("test fileId") {
            // uncomment below to test the property
            // modelInstance.fileId shouldBe ("TODO")
        }

        // to test the property `tools` - The tools to add this file to.
        should("test tools") {
            // uncomment below to test the property
            // modelInstance.tools shouldBe ("TODO")
        }
    }
}
