/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openai.models.CreateAssistantRequestToolResourcesFileSearchVectorStoresInnerChunkingStrategy
import com.openai.models.AutoChunkingStrategy
import com.openai.models.StaticChunkingStrategy
import com.openai.models.StaticChunkingStrategyStatic

class CreateAssistantRequestToolResourcesFileSearchVectorStoresInnerChunkingStrategyTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateAssistantRequestToolResourcesFileSearchVectorStoresInnerChunkingStrategy
        //val modelInstance = CreateAssistantRequestToolResourcesFileSearchVectorStoresInnerChunkingStrategy()

        // to test the property `type` - Always `auto`.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `static`
        should("test static") {
            // uncomment below to test the property
            //modelInstance.static shouldBe ("TODO")
        }

    }
}
