/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class CreateTranscriptionResponseJsonTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // CreateTranscriptionResponseJson
        // val modelInstance = CreateTranscriptionResponseJson()

        // to test the property `text` - The transcribed text.
        should("test text") {
            // uncomment below to test the property
            // modelInstance.text shouldBe ("TODO")
        }

        // to test the property `logprobs` - The log probabilities of the tokens
        // in the transcription. Only returned with the models
        // `gpt-4o-transcribe` and `gpt-4o-mini-transcribe` if `logprobs` is
        // added to the `include` array.
        should("test logprobs") {
            // uncomment below to test the property
            // modelInstance.logprobs shouldBe ("TODO")
        }
    }
}
