/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openai.models.CreateMessageRequestAttachmentsInnerToolsInner
import com.openai.models.AssistantToolsCode
import com.openai.models.AssistantToolsFileSearchTypeOnly

class CreateMessageRequestAttachmentsInnerToolsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateMessageRequestAttachmentsInnerToolsInner
        //val modelInstance = CreateMessageRequestAttachmentsInnerToolsInner()

        // to test the property `type` - The type of tool being defined: `code_interpreter`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

    }
}
