/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openai.models.CreateChatCompletionRequestFunctionCall
import com.openai.models.ChatCompletionFunctionCallOption

class CreateChatCompletionRequestFunctionCallTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateChatCompletionRequestFunctionCall
        //val modelInstance = CreateChatCompletionRequestFunctionCall()

        // to test the property `name` - The name of the function to call.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

    }
}
