/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openai.models.CreateThreadRequestToolResources
import com.openai.models.CreateAssistantRequestToolResourcesCodeInterpreter
import com.openai.models.CreateThreadRequestToolResourcesFileSearch

class CreateThreadRequestToolResourcesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateThreadRequestToolResources
        //val modelInstance = CreateThreadRequestToolResources()

        // to test the property `codeInterpreter`
        should("test codeInterpreter") {
            // uncomment below to test the property
            //modelInstance.codeInterpreter shouldBe ("TODO")
        }

        // to test the property `fileSearch`
        should("test fileSearch") {
            // uncomment below to test the property
            //modelInstance.fileSearch shouldBe ("TODO")
        }

    }
}
