/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class CreateFineTuningCheckpointPermissionRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // CreateFineTuningCheckpointPermissionRequest
        // val modelInstance = CreateFineTuningCheckpointPermissionRequest()

        // to test the property `projectIds` - The project identifiers to grant
        // access to.
        should("test projectIds") {
            // uncomment below to test the property
            // modelInstance.projectIds shouldBe ("TODO")
        }
    }
}
