/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class DefaultProjectErrorResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DefaultProjectErrorResponse
        // val modelInstance = DefaultProjectErrorResponse()

        // to test the property `code`
        should("test code") {
            // uncomment below to test the property
            // modelInstance.code shouldBe ("TODO")
        }

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            // modelInstance.message shouldBe ("TODO")
        }
    }
}
