/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class DoubleClickTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DoubleClick
        // val modelInstance = DoubleClick()

        // to test the property `type` - Specifies the event type. For a double
        // click action, this property is  always set to `double_click`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `x` - The x-coordinate where the double click
        // occurred.
        should("test x") {
            // uncomment below to test the property
            // modelInstance.x shouldBe ("TODO")
        }

        // to test the property `y` - The y-coordinate where the double click
        // occurred.
        should("test y") {
            // uncomment below to test the property
            // modelInstance.y shouldBe ("TODO")
        }
    }
}
