/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class FileSearchToolCallResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // FileSearchToolCallResultsInner
        // val modelInstance = FileSearchToolCallResultsInner()

        // to test the property `fileId` - The unique ID of the file.
        should("test fileId") {
            // uncomment below to test the property
            // modelInstance.fileId shouldBe ("TODO")
        }

        // to test the property `text` - The text that was retrieved from the
        // file.
        should("test text") {
            // uncomment below to test the property
            // modelInstance.text shouldBe ("TODO")
        }

        // to test the property `filename` - The name of the file.
        should("test filename") {
            // uncomment below to test the property
            // modelInstance.filename shouldBe ("TODO")
        }

        // to test the property `attributes` - Set of 16 key-value pairs that
        // can be attached to an object. This can be  useful for storing
        // additional information about the object in a structured  format, and
        // querying for objects via API or the dashboard. Keys are strings  with
        // a maximum length of 64 characters. Values are strings with a maximum
        // length of 512 characters, booleans, or numbers.
        should("test attributes") {
            // uncomment below to test the property
            // modelInstance.attributes shouldBe ("TODO")
        }

        // to test the property `score` - The relevance score of the file - a
        // value between 0 and 1.
        should("test score") {
            // uncomment below to test the property
            // modelInstance.score shouldBe ("TODO")
        }
    }
}
