/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class FileCitationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FileCitation
        // val modelInstance = FileCitation()

        // to test the property `type` - The type of the file citation. Always
        // `file_citation`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `index` - The index of the file in the list of
        // files.
        should("test index") {
            // uncomment below to test the property
            // modelInstance.index shouldBe ("TODO")
        }

        // to test the property `fileId` - The ID of the file.
        should("test fileId") {
            // uncomment below to test the property
            // modelInstance.fileId shouldBe ("TODO")
        }
    }
}
