/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class FineTuneMethodTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FineTuneMethod
        // val modelInstance = FineTuneMethod()

        // to test the property `type` - The type of method. Is either
        // `supervised` or `dpo`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `supervised`
        should("test supervised") {
            // uncomment below to test the property
            // modelInstance.supervised shouldBe ("TODO")
        }

        // to test the property `dpo`
        should("test dpo") {
            // uncomment below to test the property
            // modelInstance.dpo shouldBe ("TODO")
        }
    }
}
