/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openai.models.FineTuneDPOMethodHyperparametersBatchSize

class FineTuneDPOMethodHyperparametersBatchSizeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FineTuneDPOMethodHyperparametersBatchSize
        //val modelInstance = FineTuneDPOMethodHyperparametersBatchSize()

    }
}
