/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class FineTuneDPOMethodTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FineTuneDPOMethod
        // val modelInstance = FineTuneDPOMethod()

        // to test the property `hyperparameters`
        should("test hyperparameters") {
            // uncomment below to test the property
            // modelInstance.hyperparameters shouldBe ("TODO")
        }
    }
}
