/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openai.models.FineTuneSupervisedMethod
import com.openai.models.FineTuneSupervisedMethodHyperparameters

class FineTuneSupervisedMethodTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FineTuneSupervisedMethod
        //val modelInstance = FineTuneSupervisedMethod()

        // to test the property `hyperparameters`
        should("test hyperparameters") {
            // uncomment below to test the property
            //modelInstance.hyperparameters shouldBe ("TODO")
        }

    }
}
