/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openai.models.FineTuneChatRequestInput
import com.openai.models.ChatCompletionFunctions
import com.openai.models.ChatCompletionTool
import com.openai.models.FineTuneChatRequestInputMessagesInner

class FineTuneChatRequestInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FineTuneChatRequestInput
        //val modelInstance = FineTuneChatRequestInput()

        // to test the property `messages`
        should("test messages") {
            // uncomment below to test the property
            //modelInstance.messages shouldBe ("TODO")
        }

        // to test the property `tools` - A list of tools the model may generate JSON inputs for.
        should("test tools") {
            // uncomment below to test the property
            //modelInstance.tools shouldBe ("TODO")
        }

        // to test the property `parallelToolCalls` - Whether to enable [parallel function calling](/docs/guides/function-calling#configuring-parallel-function-calling) during tool use.
        should("test parallelToolCalls") {
            // uncomment below to test the property
            //modelInstance.parallelToolCalls shouldBe ("TODO")
        }

        // to test the property `functions` - A list of functions the model may generate JSON inputs for.
        should("test functions") {
            // uncomment below to test the property
            //modelInstance.functions shouldBe ("TODO")
        }

    }
}
