/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class FineTuneDPOMethodHyperparametersLearningRateMultiplierTest :
    ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // FineTuneDPOMethodHyperparametersLearningRateMultiplier
        // val modelInstance =
        // FineTuneDPOMethodHyperparametersLearningRateMultiplier()

    }
}
