/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class FineTuningCheckpointPermissionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // FineTuningCheckpointPermission
        // val modelInstance = FineTuningCheckpointPermission()

        // to test the property `id` - The permission identifier, which can be
        // referenced in the API endpoints.
        should("test id") {
            // uncomment below to test the property
            // modelInstance.id shouldBe ("TODO")
        }

        // to test the property `createdAt` - The Unix timestamp (in seconds)
        // for when the permission was created.
        should("test createdAt") {
            // uncomment below to test the property
            // modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `projectId` - The project identifier that the
        // permission is for.
        should("test projectId") {
            // uncomment below to test the property
            // modelInstance.projectId shouldBe ("TODO")
        }

        // to test the property ``object`` - The object type, which is always
        // \"checkpoint.permission\".
        should("test `object`") {
            // uncomment below to test the property
            // modelInstance.`object` shouldBe ("TODO")
        }
    }
}
