/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class FunctionToolCallOutputResourceTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // FunctionToolCallOutputResource
        // val modelInstance = FunctionToolCallOutputResource()

        // to test the property `id` - The unique ID of the function call tool
        // output.
        should("test id") {
            // uncomment below to test the property
            // modelInstance.id shouldBe ("TODO")
        }

        // to test the property `type` - The type of the function tool call
        // output. Always `function_call_output`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `callId` - The unique ID of the function tool
        // call generated by the model.
        should("test callId") {
            // uncomment below to test the property
            // modelInstance.callId shouldBe ("TODO")
        }

        // to test the property `output` - A JSON string of the output of the
        // function tool call.
        should("test output") {
            // uncomment below to test the property
            // modelInstance.output shouldBe ("TODO")
        }

        // to test the property `status` - The status of the item. One of
        // `in_progress`, `completed`, or `incomplete`. Populated when items are
        // returned via API.
        should("test status") {
            // uncomment below to test the property
            // modelInstance.status shouldBe ("TODO")
        }
    }
}
