/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class InputMessageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InputMessage
        // val modelInstance = InputMessage()

        // to test the property `role` - The role of the message input. One of
        // `user`, `system`, or `developer`.
        should("test role") {
            // uncomment below to test the property
            // modelInstance.role shouldBe ("TODO")
        }

        // to test the property `content` - A list of one or many input items to
        // the model, containing different content  types.
        should("test content") {
            // uncomment below to test the property
            // modelInstance.content shouldBe ("TODO")
        }

        // to test the property `type` - The type of the message input. Always
        // set to `message`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `status` - The status of item. One of
        // `in_progress`, `completed`, or `incomplete`. Populated when items are
        // returned via API.
        should("test status") {
            // uncomment below to test the property
            // modelInstance.status shouldBe ("TODO")
        }
    }
}
