/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class InputImageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InputImage
        // val modelInstance = InputImage()

        // to test the property `type` - The type of the input item. Always
        // `input_image`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `detail` - The detail level of the image to be
        // sent to the model. One of `high`, `low`, or `auto`. Defaults to
        // `auto`.
        should("test detail") {
            // uncomment below to test the property
            // modelInstance.detail shouldBe ("TODO")
        }

        // to test the property `imageUrl` - The URL of the image to be sent to
        // the model. A fully qualified URL or base64 encoded image in a data
        // URL.
        should("test imageUrl") {
            // uncomment below to test the property
            // modelInstance.imageUrl shouldBe ("TODO")
        }

        // to test the property `fileId` - The ID of the file to be sent to the
        // model.
        should("test fileId") {
            // uncomment below to test the property
            // modelInstance.fileId shouldBe ("TODO")
        }
    }
}
