/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class KeyPressTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of KeyPress
        // val modelInstance = KeyPress()

        // to test the property `type` - Specifies the event type. For a
        // keypress action, this property is  always set to `keypress`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `propertyKeys` - The combination of keys the
        // model is requesting to be pressed. This is an array of strings, each
        // representing a key.
        should("test propertyKeys") {
            // uncomment below to test the property
            // modelInstance.propertyKeys shouldBe ("TODO")
        }
    }
}
