/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class LogProbTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LogProb
        // val modelInstance = LogProb()

        // to test the property `token` - The token that was used to generate
        // the log probability.
        should("test token") {
            // uncomment below to test the property
            // modelInstance.token shouldBe ("TODO")
        }

        // to test the property `logprob` - The log probability of the token.
        should("test logprob") {
            // uncomment below to test the property
            // modelInstance.logprob shouldBe ("TODO")
        }

        // to test the property `bytes` - The bytes that were used to generate
        // the log probability.
        should("test bytes") {
            // uncomment below to test the property
            // modelInstance.bytes shouldBe ("TODO")
        }

        // to test the property `topLogprobs`
        should("test topLogprobs") {
            // uncomment below to test the property
            // modelInstance.topLogprobs shouldBe ("TODO")
        }
    }
}
