/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class MessageObjectIncompleteDetailsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // MessageObjectIncompleteDetails
        // val modelInstance = MessageObjectIncompleteDetails()

        // to test the property `reason` - The reason the message is incomplete.
        should("test reason") {
            // uncomment below to test the property
            // modelInstance.reason shouldBe ("TODO")
        }
    }
}
