/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class MessageDeltaObjectDeltaTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MessageDeltaObjectDelta
        // val modelInstance = MessageDeltaObjectDelta()

        // to test the property `role` - The entity that produced the message.
        // One of `user` or `assistant`.
        should("test role") {
            // uncomment below to test the property
            // modelInstance.role shouldBe ("TODO")
        }

        // to test the property `content` - The content of the message in array
        // of text and/or images.
        should("test content") {
            // uncomment below to test the property
            // modelInstance.content shouldBe ("TODO")
        }
    }
}
