/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class MessageStreamEventTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MessageStreamEvent
        // val modelInstance = MessageStreamEvent()

        // to test the property `event`
        should("test event") {
            // uncomment below to test the property
            // modelInstance.event shouldBe ("TODO")
        }

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            // modelInstance.`data` shouldBe ("TODO")
        }
    }
}
