/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openai.models.MessageDeltaContentTextObject
import com.openai.models.MessageDeltaContentTextObjectText

class MessageDeltaContentTextObjectTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MessageDeltaContentTextObject
        //val modelInstance = MessageDeltaContentTextObject()

        // to test the property `index` - The index of the content part in the message.
        should("test index") {
            // uncomment below to test the property
            //modelInstance.index shouldBe ("TODO")
        }

        // to test the property `type` - Always `text`.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `text`
        should("test text") {
            // uncomment below to test the property
            //modelInstance.text shouldBe ("TODO")
        }

    }
}
