/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class MessageDeltaContentTextAnnotationsFileCitationObjectFileCitationTest :
    ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // MessageDeltaContentTextAnnotationsFileCitationObjectFileCitation
        // val modelInstance =
        // MessageDeltaContentTextAnnotationsFileCitationObjectFileCitation()

        // to test the property `fileId` - The ID of the specific File the
        // citation is from.
        should("test fileId") {
            // uncomment below to test the property
            // modelInstance.fileId shouldBe ("TODO")
        }

        // to test the property `quote` - The specific quote in the file.
        should("test quote") {
            // uncomment below to test the property
            // modelInstance.quote shouldBe ("TODO")
        }
    }
}
