/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ModelResponsePropertiesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ModelResponseProperties
        // val modelInstance = ModelResponseProperties()

        // to test the property `metadata` - Set of 16 key-value pairs that can
        // be attached to an object. This can be useful for storing additional
        // information about the object in a structured format, and querying for
        // objects via API or the dashboard.   Keys are strings with a maximum
        // length of 64 characters. Values are strings with a maximum length of
        // 512 characters.
        should("test metadata") {
            // uncomment below to test the property
            // modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `temperature` - What sampling temperature to
        // use, between 0 and 2. Higher values like 0.8 will make the output
        // more random, while lower values like 0.2 will make it more focused
        // and deterministic. We generally recommend altering this or `top_p`
        // but not both.
        should("test temperature") {
            // uncomment below to test the property
            // modelInstance.temperature shouldBe ("TODO")
        }

        // to test the property `topP` - An alternative to sampling with
        // temperature, called nucleus sampling, where the model considers the
        // results of the tokens with top_p probability mass. So 0.1 means only
        // the tokens comprising the top 10% probability mass are considered.
        // We generally recommend altering this or `temperature` but not both.
        should("test topP") {
            // uncomment below to test the property
            // modelInstance.topP shouldBe ("TODO")
        }

        // to test the property `user` - A unique identifier representing your
        // end-user, which can help OpenAI to monitor and detect abuse. [Learn
        // more](/docs/guides/safety-best-practices#end-user-ids).
        should("test user") {
            // uncomment below to test the property
            // modelInstance.user shouldBe ("TODO")
        }
    }
}
