/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ModifyThreadRequestToolResourcesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // ModifyThreadRequestToolResources
        // val modelInstance = ModifyThreadRequestToolResources()

        // to test the property `codeInterpreter`
        should("test codeInterpreter") {
            // uncomment below to test the property
            // modelInstance.codeInterpreter shouldBe ("TODO")
        }

        // to test the property `fileSearch`
        should("test fileSearch") {
            // uncomment below to test the property
            // modelInstance.fileSearch shouldBe ("TODO")
        }
    }
}
