/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class MoveTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Move
        // val modelInstance = Move()

        // to test the property `type` - Specifies the event type. For a move
        // action, this property is  always set to `move`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `x` - The x-coordinate to move to.
        should("test x") {
            // uncomment below to test the property
            // modelInstance.x shouldBe ("TODO")
        }

        // to test the property `y` - The y-coordinate to move to.
        should("test y") {
            // uncomment below to test the property
            // modelInstance.y shouldBe ("TODO")
        }
    }
}
