/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class OutputItemTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OutputItem
        // val modelInstance = OutputItem()

        // to test the property `id` - The unique identifier of the reasoning
        // content.
        should("test id") {
            // uncomment below to test the property
            // modelInstance.id shouldBe ("TODO")
        }

        // to test the property `type` - The type of the output message. Always
        // `message`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `role` - The role of the output message. Always
        // `assistant`.
        should("test role") {
            // uncomment below to test the property
            // modelInstance.role shouldBe ("TODO")
        }

        // to test the property `content` - The content of the output message.
        should("test content") {
            // uncomment below to test the property
            // modelInstance.content shouldBe ("TODO")
        }

        // to test the property `status` - The status of the item. One of
        // `in_progress`, `completed`, or `incomplete`. Populated when items are
        // returned via API.
        should("test status") {
            // uncomment below to test the property
            // modelInstance.status shouldBe ("TODO")
        }

        // to test the property `queries` - The queries used to search for
        // files.
        should("test queries") {
            // uncomment below to test the property
            // modelInstance.queries shouldBe ("TODO")
        }

        // to test the property `callId` - An identifier used when responding to
        // the tool call with output.
        should("test callId") {
            // uncomment below to test the property
            // modelInstance.callId shouldBe ("TODO")
        }

        // to test the property `name` - The name of the function to run.
        should("test name") {
            // uncomment below to test the property
            // modelInstance.name shouldBe ("TODO")
        }

        // to test the property `arguments` - A JSON string of the arguments to
        // pass to the function.
        should("test arguments") {
            // uncomment below to test the property
            // modelInstance.arguments shouldBe ("TODO")
        }

        // to test the property `action`
        should("test action") {
            // uncomment below to test the property
            // modelInstance.action shouldBe ("TODO")
        }

        // to test the property `pendingSafetyChecks` - The pending safety
        // checks for the computer call.
        should("test pendingSafetyChecks") {
            // uncomment below to test the property
            // modelInstance.pendingSafetyChecks shouldBe ("TODO")
        }

        // to test the property `summary` - Reasoning text contents.
        should("test summary") {
            // uncomment below to test the property
            // modelInstance.summary shouldBe ("TODO")
        }

        // to test the property `results` - The results of the file search tool
        // call.
        should("test results") {
            // uncomment below to test the property
            // modelInstance.results shouldBe ("TODO")
        }
    }
}
