/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class OutputAudioTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OutputAudio
        // val modelInstance = OutputAudio()

        // to test the property `type` - The type of the output audio. Always
        // `output_audio`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property ``data`` - Base64-encoded audio data from the
        // model.
        should("test `data`") {
            // uncomment below to test the property
            // modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `transcript` - The transcript of the audio data
        // from the model.
        should("test transcript") {
            // uncomment below to test the property
            // modelInstance.transcript shouldBe ("TODO")
        }
    }
}
