/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ProjectCreateRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProjectCreateRequest
        // val modelInstance = ProjectCreateRequest()

        // to test the property `name` - The friendly name of the project, this
        // name appears in reports.
        should("test name") {
            // uncomment below to test the property
            // modelInstance.name shouldBe ("TODO")
        }
    }
}
