/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class RealtimeSessionInputAudioTranscriptionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // RealtimeSessionInputAudioTranscription
        // val modelInstance = RealtimeSessionInputAudioTranscription()

        // to test the property `model` - The model to use for transcription,
        // `whisper-1` is the only currently  supported model.
        should("test model") {
            // uncomment below to test the property
            // modelInstance.model shouldBe ("TODO")
        }
    }
}
