/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class RealtimeTranscriptionSessionCreateRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // RealtimeTranscriptionSessionCreateRequest
        // val modelInstance = RealtimeTranscriptionSessionCreateRequest()

        // to test the property `modalities` - The set of modalities the model
        // can respond with. To disable audio, set this to [\"text\"].
        should("test modalities") {
            // uncomment below to test the property
            // modelInstance.modalities shouldBe ("TODO")
        }

        // to test the property `inputAudioFormat` - The format of input audio.
        // Options are `pcm16`, `g711_ulaw`, or `g711_alaw`. For `pcm16`, input
        // audio must be 16-bit PCM at a 24kHz sample rate,  single channel
        // (mono), and little-endian byte order.
        should("test inputAudioFormat") {
            // uncomment below to test the property
            // modelInstance.inputAudioFormat shouldBe ("TODO")
        }

        // to test the property `inputAudioTranscription`
        should("test inputAudioTranscription") {
            // uncomment below to test the property
            // modelInstance.inputAudioTranscription shouldBe ("TODO")
        }

        // to test the property `turnDetection`
        should("test turnDetection") {
            // uncomment below to test the property
            // modelInstance.turnDetection shouldBe ("TODO")
        }

        // to test the property `inputAudioNoiseReduction`
        should("test inputAudioNoiseReduction") {
            // uncomment below to test the property
            // modelInstance.inputAudioNoiseReduction shouldBe ("TODO")
        }

        // to test the property `include` - The set of items to include in the
        // transcription. Current available items are: -
        // `item.input_audio_transcription.logprobs`
        should("test include") {
            // uncomment below to test the property
            // modelInstance.include shouldBe ("TODO")
        }
    }
}
