/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class RealtimeClientEventConversationItemRetrieveTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // RealtimeClientEventConversationItemRetrieve
        // val modelInstance = RealtimeClientEventConversationItemRetrieve()

        // to test the property `type` - The event type, must be
        // `conversation.item.retrieve`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `itemId` - The ID of the item to retrieve.
        should("test itemId") {
            // uncomment below to test the property
            // modelInstance.itemId shouldBe ("TODO")
        }

        // to test the property `eventId` - Optional client-generated ID used to
        // identify this event.
        should("test eventId") {
            // uncomment below to test the property
            // modelInstance.eventId shouldBe ("TODO")
        }
    }
}
