/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class RealtimeServerEventConversationItemInputAudioTranscriptionDeltaTest :
    ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // RealtimeServerEventConversationItemInputAudioTranscriptionDelta
        // val modelInstance =
        // RealtimeServerEventConversationItemInputAudioTranscriptionDelta()

        // to test the property `eventId` - The unique ID of the server event.
        should("test eventId") {
            // uncomment below to test the property
            // modelInstance.eventId shouldBe ("TODO")
        }

        // to test the property `type` - The event type, must be
        // `conversation.item.input_audio_transcription.delta`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `itemId` - The ID of the item.
        should("test itemId") {
            // uncomment below to test the property
            // modelInstance.itemId shouldBe ("TODO")
        }

        // to test the property `contentIndex` - The index of the content part
        // in the item's content array.
        should("test contentIndex") {
            // uncomment below to test the property
            // modelInstance.contentIndex shouldBe ("TODO")
        }

        // to test the property `delta` - The text delta.
        should("test delta") {
            // uncomment below to test the property
            // modelInstance.delta shouldBe ("TODO")
        }

        // to test the property `logprobs` - The log probabilities of the
        // transcription.
        should("test logprobs") {
            // uncomment below to test the property
            // modelInstance.logprobs shouldBe ("TODO")
        }
    }
}
