/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class RealtimeSessionInputAudioNoiseReductionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // RealtimeSessionInputAudioNoiseReduction
        // val modelInstance = RealtimeSessionInputAudioNoiseReduction()

        // to test the property `type` - Type of noise reduction. `near_field`
        // is for close-talking microphones such as headphones, `far_field` is
        // for far-field microphones such as laptop or conference room
        // microphones.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }
    }
}
