/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ReasoningItemSummaryInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReasoningItemSummaryInner
        // val modelInstance = ReasoningItemSummaryInner()

        // to test the property `type` - The type of the object. Always
        // `summary_text`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `text` - A short summary of the reasoning used
        // by the model when generating the response.
        should("test text") {
            // uncomment below to test the property
            // modelInstance.text shouldBe ("TODO")
        }
    }
}
