/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ReasoningTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Reasoning
        // val modelInstance = Reasoning()

        // to test the property `effort`
        should("test effort") {
            // uncomment below to test the property
            // modelInstance.effort shouldBe ("TODO")
        }

        // to test the property `generateSummary` - **computer_use_preview
        // only**  A summary of the reasoning performed by the model. This can
        // be useful for debugging and understanding the model's reasoning
        // process. One of `concise` or `detailed`.
        should("test generateSummary") {
            // uncomment below to test the property
            // modelInstance.generateSummary shouldBe ("TODO")
        }
    }
}
