/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class RefusalTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Refusal
        // val modelInstance = Refusal()

        // to test the property `type` - The type of the refusal. Always
        // `refusal`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `refusal` - The refusal explanationfrom the
        // model.
        should("test refusal") {
            // uncomment below to test the property
            // modelInstance.refusal shouldBe ("TODO")
        }
    }
}
