/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ResponseCodeInterpreterCallCodeDoneEventTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // ResponseCodeInterpreterCallCodeDoneEvent
        // val modelInstance = ResponseCodeInterpreterCallCodeDoneEvent()

        // to test the property `type` - The type of the event. Always
        // `response.code_interpreter_call.code.done`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `outputIndex` - The index of the output item
        // that the code interpreter call is in progress.
        should("test outputIndex") {
            // uncomment below to test the property
            // modelInstance.outputIndex shouldBe ("TODO")
        }

        // to test the property `code` - The final code snippet output by the
        // code interpreter.
        should("test code") {
            // uncomment below to test the property
            // modelInstance.code shouldBe ("TODO")
        }
    }
}
