/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ResponseStreamEventTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResponseStreamEvent
        // val modelInstance = ResponseStreamEvent()

        // to test the property `type` - The type of the event. Always
        // `response.audio.delta`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `delta` - The text delta that was added.
        should("test delta") {
            // uncomment below to test the property
            // modelInstance.delta shouldBe ("TODO")
        }

        // to test the property `outputIndex` - The index of the output item
        // that the web search call is associated with.
        should("test outputIndex") {
            // uncomment below to test the property
            // modelInstance.outputIndex shouldBe ("TODO")
        }

        // to test the property `code` - The error code.
        should("test code") {
            // uncomment below to test the property
            // modelInstance.code shouldBe ("TODO")
        }

        // to test the property `codeInterpreterCall`
        should("test codeInterpreterCall") {
            // uncomment below to test the property
            // modelInstance.codeInterpreterCall shouldBe ("TODO")
        }

        // to test the property `response`
        should("test response") {
            // uncomment below to test the property
            // modelInstance.response shouldBe ("TODO")
        }

        // to test the property `itemId` - Unique ID for the output item
        // associated with the web search call.
        should("test itemId") {
            // uncomment below to test the property
            // modelInstance.itemId shouldBe ("TODO")
        }

        // to test the property `contentIndex` - The index of the content part
        // that the text content is finalized.
        should("test contentIndex") {
            // uncomment below to test the property
            // modelInstance.contentIndex shouldBe ("TODO")
        }

        // to test the property `part`
        should("test part") {
            // uncomment below to test the property
            // modelInstance.part shouldBe ("TODO")
        }

        // to test the property `message` - The error message.
        should("test message") {
            // uncomment below to test the property
            // modelInstance.message shouldBe ("TODO")
        }

        // to test the property ``param`` - The error parameter.
        should("test `param`") {
            // uncomment below to test the property
            // modelInstance.`param` shouldBe ("TODO")
        }

        // to test the property `arguments` - The function-call arguments.
        should("test arguments") {
            // uncomment below to test the property
            // modelInstance.arguments shouldBe ("TODO")
        }

        // to test the property `item`
        should("test item") {
            // uncomment below to test the property
            // modelInstance.item shouldBe ("TODO")
        }

        // to test the property `refusal` - The refusal text that is finalized.
        should("test refusal") {
            // uncomment below to test the property
            // modelInstance.refusal shouldBe ("TODO")
        }

        // to test the property `annotationIndex` - The index of the annotation
        // that was added.
        should("test annotationIndex") {
            // uncomment below to test the property
            // modelInstance.annotationIndex shouldBe ("TODO")
        }

        // to test the property ``annotation``
        should("test `annotation`") {
            // uncomment below to test the property
            // modelInstance.`annotation` shouldBe ("TODO")
        }

        // to test the property `text` - The text content that is finalized.
        should("test text") {
            // uncomment below to test the property
            // modelInstance.text shouldBe ("TODO")
        }
    }
}
