/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ResponseUsageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResponseUsage
        // val modelInstance = ResponseUsage()

        // to test the property `inputTokens` - The number of input tokens.
        should("test inputTokens") {
            // uncomment below to test the property
            // modelInstance.inputTokens shouldBe ("TODO")
        }

        // to test the property `inputTokensDetails`
        should("test inputTokensDetails") {
            // uncomment below to test the property
            // modelInstance.inputTokensDetails shouldBe ("TODO")
        }

        // to test the property `outputTokens` - The number of output tokens.
        should("test outputTokens") {
            // uncomment below to test the property
            // modelInstance.outputTokens shouldBe ("TODO")
        }

        // to test the property `outputTokensDetails`
        should("test outputTokensDetails") {
            // uncomment below to test the property
            // modelInstance.outputTokensDetails shouldBe ("TODO")
        }

        // to test the property `totalTokens` - The total number of tokens used.
        should("test totalTokens") {
            // uncomment below to test the property
            // modelInstance.totalTokens shouldBe ("TODO")
        }
    }
}
