/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ResponseTextAnnotationDeltaEventTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // ResponseTextAnnotationDeltaEvent
        // val modelInstance = ResponseTextAnnotationDeltaEvent()

        // to test the property `type` - The type of the event. Always
        // `response.output_text.annotation.added`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `itemId` - The ID of the output item that the
        // text annotation was added to.
        should("test itemId") {
            // uncomment below to test the property
            // modelInstance.itemId shouldBe ("TODO")
        }

        // to test the property `outputIndex` - The index of the output item
        // that the text annotation was added to.
        should("test outputIndex") {
            // uncomment below to test the property
            // modelInstance.outputIndex shouldBe ("TODO")
        }

        // to test the property `contentIndex` - The index of the content part
        // that the text annotation was added to.
        should("test contentIndex") {
            // uncomment below to test the property
            // modelInstance.contentIndex shouldBe ("TODO")
        }

        // to test the property `annotationIndex` - The index of the annotation
        // that was added.
        should("test annotationIndex") {
            // uncomment below to test the property
            // modelInstance.annotationIndex shouldBe ("TODO")
        }

        // to test the property ``annotation``
        should("test `annotation`") {
            // uncomment below to test the property
            // modelInstance.`annotation` shouldBe ("TODO")
        }
    }
}
