/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ResponsePropertiesTextTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResponsePropertiesText
        // val modelInstance = ResponsePropertiesText()

        // to test the property `format`
        should("test format") {
            // uncomment below to test the property
            // modelInstance.format shouldBe ("TODO")
        }
    }
}
