/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ResponseOutputItemAddedEventTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResponseOutputItemAddedEvent
        // val modelInstance = ResponseOutputItemAddedEvent()

        // to test the property `type` - The type of the event. Always
        // `response.output_item.added`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `outputIndex` - The index of the output item
        // that was added.
        should("test outputIndex") {
            // uncomment below to test the property
            // modelInstance.outputIndex shouldBe ("TODO")
        }

        // to test the property `item`
        should("test item") {
            // uncomment below to test the property
            // modelInstance.item shouldBe ("TODO")
        }
    }
}
