/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ResponseFileSearchCallSearchingEventTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // ResponseFileSearchCallSearchingEvent
        // val modelInstance = ResponseFileSearchCallSearchingEvent()

        // to test the property `type` - The type of the event. Always
        // `response.file_search_call.searching`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `outputIndex` - The index of the output item
        // that the file search call is searching.
        should("test outputIndex") {
            // uncomment below to test the property
            // modelInstance.outputIndex shouldBe ("TODO")
        }

        // to test the property `itemId` - The ID of the output item that the
        // file search call is initiated.
        should("test itemId") {
            // uncomment below to test the property
            // modelInstance.itemId shouldBe ("TODO")
        }
    }
}
