/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ResponseErrorEventTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResponseErrorEvent
        // val modelInstance = ResponseErrorEvent()

        // to test the property `type` - The type of the event. Always `error`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `code` - The error code.
        should("test code") {
            // uncomment below to test the property
            // modelInstance.code shouldBe ("TODO")
        }

        // to test the property `message` - The error message.
        should("test message") {
            // uncomment below to test the property
            // modelInstance.message shouldBe ("TODO")
        }

        // to test the property ``param`` - The error parameter.
        should("test `param`") {
            // uncomment below to test the property
            // modelInstance.`param` shouldBe ("TODO")
        }
    }
}
