/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ResponseFunctionCallArgumentsDoneEventTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // ResponseFunctionCallArgumentsDoneEvent
        // val modelInstance = ResponseFunctionCallArgumentsDoneEvent()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `itemId` - The ID of the item.
        should("test itemId") {
            // uncomment below to test the property
            // modelInstance.itemId shouldBe ("TODO")
        }

        // to test the property `outputIndex` - The index of the output item.
        should("test outputIndex") {
            // uncomment below to test the property
            // modelInstance.outputIndex shouldBe ("TODO")
        }

        // to test the property `arguments` - The function-call arguments.
        should("test arguments") {
            // uncomment below to test the property
            // modelInstance.arguments shouldBe ("TODO")
        }
    }
}
