/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ResponseAudioDoneEventTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResponseAudioDoneEvent
        // val modelInstance = ResponseAudioDoneEvent()

        // to test the property `type` - The type of the event. Always
        // `response.audio.done`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }
    }
}
