/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openai.models.RunObjectRequiredActionSubmitToolOutputs
import com.openai.models.RunToolCallObject

class RunObjectRequiredActionSubmitToolOutputsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RunObjectRequiredActionSubmitToolOutputs
        //val modelInstance = RunObjectRequiredActionSubmitToolOutputs()

        // to test the property `toolCalls` - A list of the relevant tool calls.
        should("test toolCalls") {
            // uncomment below to test the property
            //modelInstance.toolCalls shouldBe ("TODO")
        }

    }
}
