/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openai.models.RunStepDeltaStepDetailsMessageCreationObject
import com.openai.models.RunStepDeltaStepDetailsMessageCreationObjectMessageCreation

class RunStepDeltaStepDetailsMessageCreationObjectTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RunStepDeltaStepDetailsMessageCreationObject
        //val modelInstance = RunStepDeltaStepDetailsMessageCreationObject()

        // to test the property `type` - Always `message_creation`.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `messageCreation`
        should("test messageCreation") {
            // uncomment below to test the property
            //modelInstance.messageCreation shouldBe ("TODO")
        }

    }
}
