/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openai.models.RunStepDeltaObjectDelta
import com.openai.models.RunStepDeltaObjectDeltaStepDetails

class RunStepDeltaObjectDeltaTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RunStepDeltaObjectDelta
        //val modelInstance = RunStepDeltaObjectDelta()

        // to test the property `stepDetails`
        should("test stepDetails") {
            // uncomment below to test the property
            //modelInstance.stepDetails shouldBe ("TODO")
        }

    }
}
