/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openai.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openai.models.RunStreamEvent
import com.openai.models.RunObject
import com.openai.models.RunStreamEventOneOf
import com.openai.models.RunStreamEventOneOf1
import com.openai.models.RunStreamEventOneOf2
import com.openai.models.RunStreamEventOneOf3
import com.openai.models.RunStreamEventOneOf4
import com.openai.models.RunStreamEventOneOf5
import com.openai.models.RunStreamEventOneOf6
import com.openai.models.RunStreamEventOneOf7
import com.openai.models.RunStreamEventOneOf8
import com.openai.models.RunStreamEventOneOf9

class RunStreamEventTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RunStreamEvent
        //val modelInstance = RunStreamEvent()

        // to test the property `event`
        should("test event") {
            // uncomment below to test the property
            //modelInstance.event shouldBe ("TODO")
        }

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

    }
}
