/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class StaticChunkingStrategyResponseParamTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // StaticChunkingStrategyResponseParam
        // val modelInstance = StaticChunkingStrategyResponseParam()

        // to test the property `type` - Always `static`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `static`
        should("test static") {
            // uncomment below to test the property
            // modelInstance.static shouldBe ("TODO")
        }
    }
}
