/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class ToolTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Tool
        // val modelInstance = Tool()

        // to test the property `type` - The type of the file search tool.
        // Always `file_search`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `vectorStoreIds` - The IDs of the vector stores
        // to search.
        should("test vectorStoreIds") {
            // uncomment below to test the property
            // modelInstance.vectorStoreIds shouldBe ("TODO")
        }

        // to test the property `name` - The name of the function to call.
        should("test name") {
            // uncomment below to test the property
            // modelInstance.name shouldBe ("TODO")
        }

        // to test the property `parameters` - A JSON schema object describing
        // the parameters of the function.
        should("test parameters") {
            // uncomment below to test the property
            // modelInstance.parameters shouldBe ("TODO")
        }

        // to test the property `strict` - Whether to enforce strict parameter
        // validation. Default `true`.
        should("test strict") {
            // uncomment below to test the property
            // modelInstance.strict shouldBe ("TODO")
        }

        // to test the property `displayWidth` - The width of the computer
        // display.
        should("test displayWidth") {
            // uncomment below to test the property
            // modelInstance.displayWidth shouldBe ("TODO")
        }

        // to test the property `displayHeight` - The height of the computer
        // display.
        should("test displayHeight") {
            // uncomment below to test the property
            // modelInstance.displayHeight shouldBe ("TODO")
        }

        // to test the property `environment` - The type of computer environment
        // to control.
        should("test environment") {
            // uncomment below to test the property
            // modelInstance.environment shouldBe ("TODO")
        }

        // to test the property `maxNumResults` - The maximum number of results
        // to return. This number should be between 1  and 50 inclusive.
        should("test maxNumResults") {
            // uncomment below to test the property
            // modelInstance.maxNumResults shouldBe ("TODO")
        }

        // to test the property `filters`
        should("test filters") {
            // uncomment below to test the property
            // modelInstance.filters shouldBe ("TODO")
        }

        // to test the property `rankingOptions`
        should("test rankingOptions") {
            // uncomment below to test the property
            // modelInstance.rankingOptions shouldBe ("TODO")
        }

        // to test the property `description` - A description of the function.
        // Used by the model to determine whether or not to call the function.
        should("test description") {
            // uncomment below to test the property
            // modelInstance.description shouldBe ("TODO")
        }

        // to test the property `userLocation`
        should("test userLocation") {
            // uncomment below to test the property
            // modelInstance.userLocation shouldBe ("TODO")
        }

        // to test the property `searchContextSize`
        should("test searchContextSize") {
            // uncomment below to test the property
            // modelInstance.searchContextSize shouldBe ("TODO")
        }
    }
}
