/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class TypeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Type
        // val modelInstance = Type()

        // to test the property `type` - Specifies the event type. For a type
        // action, this property is  always set to `type`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `text` - The text to type.
        should("test text") {
            // uncomment below to test the property
            // modelInstance.text shouldBe ("TODO")
        }
    }
}
