/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class UsageTimeBucketTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UsageTimeBucket
        // val modelInstance = UsageTimeBucket()

        // to test the property ``object``
        should("test `object`") {
            // uncomment below to test the property
            // modelInstance.`object` shouldBe ("TODO")
        }

        // to test the property `startTime`
        should("test startTime") {
            // uncomment below to test the property
            // modelInstance.startTime shouldBe ("TODO")
        }

        // to test the property `endTime`
        should("test endTime") {
            // uncomment below to test the property
            // modelInstance.endTime shouldBe ("TODO")
        }

        // to test the property `result`
        should("test result") {
            // uncomment below to test the property
            // modelInstance.result shouldBe ("TODO")
        }
    }
}
