/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class UserRoleUpdateRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserRoleUpdateRequest
        // val modelInstance = UserRoleUpdateRequest()

        // to test the property `role` - `owner` or `reader`
        should("test role") {
            // uncomment below to test the property
            // modelInstance.role shouldBe ("TODO")
        }
    }
}
