/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class VectorStoreSearchResultContentObjectTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of
        // VectorStoreSearchResultContentObject
        // val modelInstance = VectorStoreSearchResultContentObject()

        // to test the property `type` - The type of content.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `text` - The text content returned from search.
        should("test text") {
            // uncomment below to test the property
            // modelInstance.text shouldBe ("TODO")
        }
    }
}
