/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class WaitTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Wait
        // val modelInstance = Wait()

        // to test the property `type` - Specifies the event type. For a wait
        // action, this property is  always set to `wait`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }
    }
}
