/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class WebSearchToolUserLocationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WebSearchToolUserLocation
        // val modelInstance = WebSearchToolUserLocation()

        // to test the property `type` - The type of location approximation.
        // Always `approximate`.
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `country` - The two-letter  [ISO country
        // code](https://en.wikipedia.org/wiki/ISO_3166-1) of the user, e.g.
        // `US`.
        should("test country") {
            // uncomment below to test the property
            // modelInstance.country shouldBe ("TODO")
        }

        // to test the property `region` - Free text input for the region of the
        // user, e.g. `California`.
        should("test region") {
            // uncomment below to test the property
            // modelInstance.region shouldBe ("TODO")
        }

        // to test the property `city` - Free text input for the city of the
        // user, e.g. `San Francisco`.
        should("test city") {
            // uncomment below to test the property
            // modelInstance.city shouldBe ("TODO")
        }

        // to test the property `timezone` - The [IANA
        // timezone](https://timeapi.io/documentation/iana-timezones)  of the
        // user, e.g. `America/Los_Angeles`.
        should("test timezone") {
            // uncomment below to test the property
            // modelInstance.timezone shouldBe ("TODO")
        }
    }
}
