/**
 * Please note: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). Do not edit this file manually.
 */
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.openai.models

import io.kotlintest.specs.ShouldSpec

class WebSearchToolTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WebSearchTool
        // val modelInstance = WebSearchTool()

        // to test the property `type` - The type of the web search tool. One
        // of: - `web_search_preview` - `web_search_preview_2025_03_11`
        should("test type") {
            // uncomment below to test the property
            // modelInstance.type shouldBe ("TODO")
        }

        // to test the property `userLocation`
        should("test userLocation") {
            // uncomment below to test the property
            // modelInstance.userLocation shouldBe ("TODO")
        }

        // to test the property `searchContextSize`
        should("test searchContextSize") {
            // uncomment below to test the property
            // modelInstance.searchContextSize shouldBe ("TODO")
        }
    }
}
